### ISSUE TITLE
System.InvalidCastException при попытке делать поиск в X509Store

### ISSUE THREAD

**Issue by Buktop365** [CryptoPro/libcore#1]
При попытке поиска сертификата по thumbrint в локальном хранилище пользователя Windows все проходит нормально, без ошибок. Но при смене хранилища на StoreLocation.LocalMachine поиск того же сертификата вызывает исключение "Unable to cast object of type 'generatedProxy_1' to type 'Internal.Cryptography.Pal.CertificatePal'.". Сертификат с ключом установлен и в хранилище пользователя и в хранилище локального компьютера
Стек:
```
   at Internal.Cryptography.Pal.StorePal.LinkFromCertificateCollection(X509Certificate2Collection certificates)
   at Internal.Cryptography.Pal.FindPal..ctor(X509Certificate2Collection findFrom, X509Certificate2Collection copyTo, Boolean validOnly)
   at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Find(X509FindType findType, Object findValue, Boolean validOnly)
```
Код:
```
        static void Main(string[] args)
        {
            LibCore.Initializer.Initialize();


            X509Certificate2 cert;
            using (var store = new X509Store(StoreName.My, StoreLocation.LocalMachine))
            {
                store.Open(OpenFlags.ReadOnly);
                cert = store.Certificates.Find(X509FindType.FindByThumbprint, "bb909058458169700aef2e81c9c98f54bf7e954e", false)[0];
            }
        }
```

**Comment by Fasjeit** [comment]
Воспроизвести ошибку с вашим кодом не удалось.

Сможете собрать архив маленького проекта, на котором детерминировано воспроизводится и приложить к нему пример сертификата, который нужно установить в хранилище?

**Comment by Buktop365** [comment]
Проект максимально маленький, прикладываю
[Testing.zip](https://github.com/CryptoPro/libcore/files/10456614/Testing.zip)
Сертификат любой, например Минцифры (прикладываю), главное чтобы он был установлен в хранилище LocalMachine
[mc.zip](https://github.com/CryptoPro/libcore/files/10456628/mc.zip)

**Comment by Fasjeit** [comment]
Всё ещё не можем воспроизвести...
Windows, установили сертификат из архива в LocalMachine, My, код выполняется без ошибок.

**Comment by Fasjeit** [comment]
CSP установлена последней релизной версии (старше 5.0.12600)?

**Comment by d1maxa** [comment]
Аналогично вылетает. Возможно ошибка возникает, когда в хранилище есть не только гост-сертификаты, а например еще rsa (алгоритм sha512RSA)

**Comment by Fasjeit** [comment]
@d1maxa У себя и смотрим на смешанном хранилище, но воспроизвести не можем

**Comment by SergeyKobyakov** [comment]
У меня на одном компе любой метод поиска по хранилищу вызывает такую проблему (Windows 11), на другом с поиском проблем нет (Windows 10). Может от винды зависит?

**Comment by Skit91** [comment]
Была также аналогичная проблема на одной из машин. Проблема в методе Find, можно обойти не используя его.

> У меня на одном компе любой метод поиска по хранилищу вызывает такую проблему (Windows 11), на другом с поиском проблем нет (Windows 10). Может от винды зависит?

**Comment by Fasjeit** [comment]
Если имеются машины, на который детерминировано воспроизводится\не воспроизводится - пришлите пожалуйста консольный вывод `dotnet --info` с них.

**Comment by SergeyKobyakov** [comment]
> Если имеются машины, на который детерминировано воспроизводится\не воспроизводится - пришлите пожалуйста консольный вывод `dotnet --info` с них.

С машины, где не работает:
[dotNetInfo_Certificates.Find-Fail.txt](https://github.com/CryptoPro/libcore/files/10685553/dotNetInfo_Certificates.Find-Fail.txt)

С машины, где работает:
[dotNetInfo_Certificates.Find-Ok.txt](https://github.com/CryptoPro/libcore/files/10685555/dotNetInfo_Certificates.Find-Ok.txt)

**Comment by Fasjeit** [comment]
Спасибо. Существенный различий, кроме версий винды (10.0.22621 vs 10.0.19044) не вижу, старшие версии рантаймов и sdk аналогичные на обоих машинах. Попробую посмотреть на старших версиях десятки.

CSP одинаковой версии на машинах?

**Comment by SergeyKobyakov** [comment]
> Спасибо. Существенный различий, кроме версий винды (10.0.22621 vs 10.0.19044) не вижу, старшие версии рантаймов и sdk аналогичные на обоих машинах. Попробую посмотреть на старших версиях.
> 
> CSP одинаковой версии на машинах?

Да, версии одинаковые: 5.0.12600 КС1

**Comment by Fasjeit** [comment]
Воспроизвели.

Причина оказалось интересной - ошибка воспроизводилась при поиске по коллекции, только если ГОСТовый сертификат в ней располагался ДО RSA сертификата. Если же RSA сертификат шёл первым - ошибка не воспроизводилась.

От версии Windows не зависит, на 11 воспроизводилось скорее из за того, что машина была "новее" и имела меньше RSA сертификатов, и был больше шанс встретить ГОСТовый сертификат первым в коллекции.

**Comment by Fasjeit** [comment]
Сборка с исправлением, которое должно помочь:
[Linux](https://file.cryptopro.ru/f/BjczVi7oruZ2U7xSGdbpwnUobglnNhcj/LibCore.Linux.2023.2.9.1.nupkg)
[Windows](https://file.cryptopro.ru/f/VLmumT1Vpremy3Jna8VhXw4FLT4RINhb/LibCore.Windows.2023.2.9.1.nupkg)

**Comment by SergeyKobyakov** [comment]
> Сборка с исправлением, которое должно помочь: [Linux](https://file.cryptopro.ru/f/CEztInDVG0XHtczKGLBdQvT9DCebolS4/LibCore.Linux.2023.2.9.1.nupkg) [Windows](https://file.cryptopro.ru/f/v1Sp2ic5R7OKcSRo7Zqdte3dxkIZC34Y/LibCore.Windows.2023.2.9.1.nupkg)

Проверил сборку под Windows, проблема решена.
