### ISSUE TITLE
Использование библиотек для Windows и Linux в одном проекте

### ISSUE THREAD

**Issue by Bykiev** [CryptoPro/libcore#10]
Здравствуйте!

Возможно ли использование библиотек для Windows и Linux одновременно в одном проекте, не будет конфликтов? Почему вообще было принято решение в виде 2 сборок, а не вызов нужного метода в зависимости от целевой платформы?

**Comment by Fasjeit** [comment]
Добрый день.

Одновременно использовать точно не стоит.

Основной сценарий использования - иметь возможность собрать целевой проект с использованием LibCore как для Windows, так и для Linux, причём вне зависимости от сборочной платформы. Для каждой целевой ОС в результате получается свой собранный проект, в котором нет проверок ОС во время выполнения.

В csproj достаточно прописать условие использования того или иного nuget пакета в зависимости от таргета (целевой платформы). 

Выглядит это как то так:

```xml
<ItemGroup Condition="'$(TargetsWindows)' == 'true'">
    <PackageReference Include="LibCore.Windows" Version="2023.X.X.1" />
</ItemGroup>
<ItemGroup Condition="'$(TargetsUnix)' == 'true'">
    <PackageReference Include="LibCore.Linux" Version="2023.X.X.1" />
</ItemGroup>
``` 

где `TargetsWindows` и `TargetsUnix` вы должны определить самостоятельно, например так
```xml
<PropertyGroup Label="CalculateTargetOS">
    <_hostOS>linux</_hostOS>
    <_hostOS Condition="$([MSBuild]::IsOSPlatform('WINDOWS'))">windows</_hostOS>
    <TargetOS Condition="'$(TargetOS)' == ''">$(_hostOS)</TargetOS>
</PropertyGroup>
<PropertyGroup Label="CalculateTargetOSName">
    <TargetsLinux Condition="'$(TargetOS)' == 'linux'">true</TargetsLinux>
    <TargetsWindows Condition="'$(TargetOS)' == 'windows'">true</TargetsWindows>
</PropertyGroup>
<PropertyGroup>
    <DefineConstants Condition="'$(TargetsLinux)' == 'true'">$(DefineConstants);TargetsLinux</DefineConstants>
    <DefineConstants Condition="'$(TargetsWindows)' == 'true'">$(DefineConstants);TargetsWindows</DefineConstants>
</PropertyGroup>
```

По умолчанию будет собираться проект под текущую ОС, при сборке через`dotnet build -p:TargetOS=linux` будет собираться версия для Linux, `dotnet build -p:TargetOS=windows` - для windows. Аналогично и для `dotnet pack`.

**Comment by Bykiev** [comment]
Спасибо, а если вынести работу с ЭЦП в 2 отдельных сборки для Windows и Linux и в зависимости от платформы вызывать метод из нужно, то не будет работать?

**Comment by Fasjeit** [comment]
Так сработает, т.е. делаете 2 сборки `Сборка.Linux` и `Сборка.Windows` с разными неймспейсами и\или названиями функций и вызываете нужную.

**Comment by Bykiev** [comment]
> Так сработает, т.е. делаете 2 сборки `Сборка.Linux` и `Сборка.Windows` с разными неймспейсами и\или названиями функций и вызываете нужную.

И все же так не работает: выдает на Windows ошибку: `Unable to load DLL 'libcapi20' or one of its dependencies: Не найден указанный модуль. (0x8007007E)"`, хотя в коде прописываю условия:
```
bool isWindows = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
if (isWindows){
....
}
else {
...
}
```
Для сборки Линукс в файле проекта прописал `<RuntimeIdentifier>linux-x64</RuntimeIdentifier>`, для Windows - `<RuntimeIdentifier>win-x64</RuntimeIdentifier>`.

Версия LibCore 2023.3.16.1. Что еще нужно сделать, чтобы в зависимости от ОС подгружалась только нужная библиотека?

**Comment by Fasjeit** [comment]
Да, ошибся выше. Проблема в том, что грузится только одна транзитивная зависимость от LibCore, какая по мнению msbuild сборок будет первая. В вашем случае загрузилась первой сборка Linux - и пытается её использовать.

**TLDR**: Нужно вручную прогружать сборки до первого вызова. Как можно сделать иначе на уровне LibCore - подумаем, но не обещаем, что выйдет что либо проще.

Красивого решения, кроме как вручную предзагружать нужную сборки не вижу.
План такой:
* собираем библиотеку Linux с зависимостью от LibCore.Linux
* собираем библиотеку Windows с зависимостью от LibCore.Windows
* собираем целевой проект с зависимостями от библиотек Linux и Windows
* после сборки целевого проекта удаляем из папки bin сборки LibCore.*.dll (можно сделать через post build events)
* создаём папки Windows и Linux в bin целевого проекта, кладём в них сборки LibCore из соответствующих пакетов (или из сборок Linux и Windows)

Структура файлов должна получиться следующая
```
├── 0Harmony.dll
├── LibCoreOsDependant.deps.json
├── LibCoreOsDependant.dll
├── LibCoreOsDependant.exe
├── LibCoreOsDependant.pdb
├── LibCoreOsDependant.runtimeconfig.json
├── Linux
│   ├── LibCore.Common.dll
│   ├── LibCore.dll
│   ├── LibCore.Net.Security.dll
│   ├── LibCore.Security.Cryptography.Algorithms.dll
│   ├── LibCore.Security.Cryptography.Csp.dll
│   ├── LibCore.Security.Cryptography.Pkcs.dll
│   ├── LibCore.Security.Cryptography.Primitives.dll
│   ├── LibCore.Security.Cryptography.X509Certificates.dll
│   └── LibCore.Security.Cryptography.Xml.dll
├── Linux.dll
├── Mono.Cecil.dll
├── Mono.Cecil.Mdb.dll
├── Mono.Cecil.Pdb.dll
├── Mono.Cecil.Rocks.dll
├── MonoMod.Common.dll
├── runtimes
│   └── win
│       └── lib
│           └── net6.0
│               └── System.Security.Cryptography.Pkcs.dll
├── System.Security.Cryptography.Pkcs.dll
├── System.Security.Cryptography.Xml.dll
├── Windows
│   ├── LibCore.Common.dll
│   ├── LibCore.dll
│   ├── LibCore.Net.Security.dll
│   ├── LibCore.Security.Cryptography.Algorithms.dll
│   ├── LibCore.Security.Cryptography.Csp.dll
│   ├── LibCore.Security.Cryptography.Pkcs.dll
│   ├── LibCore.Security.Cryptography.Primitives.dll
│   ├── LibCore.Security.Cryptography.X509Certificates.dll
│   └── LibCore.Security.Cryptography.Xml.dll
├── Windows.dll

```  

В самом коде целевого проекта делаем ручную загрузку сборок LibCore ДО первого вызова:
```csharp
bool isWindows = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);

if (isWindows)
{
    // pre load assemblies
    var baseWindowsFolder = @"C:\Users\user\source\repos\LibCoreOsDependant\LibCoreOsDependant\bin\Debug\net6.0\Windows\";
    Assembly.LoadFrom(Path.Combine(baseWindowsFolder + "LibCore.Common.dll"));
    Assembly.LoadFrom(Path.Combine(baseWindowsFolder + "LibCore.dll"));
    Assembly.LoadFrom(Path.Combine(baseWindowsFolder + "LibCore.Security.Cryptography.Algorithms.dll"));
    Assembly.LoadFrom(Path.Combine(baseWindowsFolder + "LibCore.Security.Cryptography.Primitives.dll"));
    Assembly.LoadFrom(Path.Combine(baseWindowsFolder + "LibCore.Security.Cryptography.Csp.dll"));
    Assembly.LoadFrom(Path.Combine(baseWindowsFolder + "LibCore.Security.Cryptography.X509Certificates.dll"));
    Assembly.LoadFrom(Path.Combine(baseWindowsFolder + "LibCore.Security.Cryptography.Pkcs.dll"));
    Assembly.LoadFrom(Path.Combine(baseWindowsFolder + "LibCore.Security.Cryptography.Xml.dll"));
    Assembly.LoadFrom(Path.Combine(baseWindowsFolder + "LibCore.Net.Security.dll"));

    // call method
    ClassWindows.Do();
}
else
{
    // pre load assemblies
    var baseLinuxFolder = @"/home/user/dev/tmp/net6.0/Linux/";
    Assembly.LoadFrom(Path.Combine(baseLinuxFolder + "LibCore.Common.dll"));
    Assembly.LoadFrom(Path.Combine(baseLinuxFolder + "LibCore.dll"));
    Assembly.LoadFrom(Path.Combine(baseLinuxFolder + "LibCore.Security.Cryptography.Algorithms.dll"));
    Assembly.LoadFrom(Path.Combine(baseLinuxFolder + "LibCore.Security.Cryptography.Primitives.dll"));
    Assembly.LoadFrom(Path.Combine(baseLinuxFolder + "LibCore.Security.Cryptography.Csp.dll"));
    Assembly.LoadFrom(Path.Combine(baseLinuxFolder + "LibCore.Security.Cryptography.X509Certificates.dll"));
    Assembly.LoadFrom(Path.Combine(baseLinuxFolder + "LibCore.Security.Cryptography.Pkcs.dll"));
    Assembly.LoadFrom(Path.Combine(baseLinuxFolder + "LibCore.Security.Cryptography.Xml.dll"));
    Assembly.LoadFrom(Path.Combine(baseLinuxFolder + "LibCore.Net.Security.dll"));

    // call method
    ClassLinux.Do();
}
```

Пример проекта, в котором не хватает только правильных путей и post build event (т.е. нужно выполнить действия из "плана" выше):
[LibCoreOsDependant.zip](https://github.com/CryptoPro/libcore/files/11033663/LibCoreOsDependant.zip)
