### ISSUE TITLE
Ошибка при вызове метода CpX509Store.Certificates.Find

### ISSUE THREAD

**Issue by Poisent** [CryptoPro/libcore#19]
Версия библиотеки: LibCore.Linux.2023.4.25.1
Ошибка: 
Unable to find an entry point named 'CertAddCertificateLinkToStore' in shared library 'libcapi20'.. HRESULT:0x80131523

Стенд:
RED OS MUROM (7.3.2)
dotnet  6.0.5
CSP (Type:80) v5.0.10003 KC1 Release Ver:5.0.11455 OS:Linux CPU:AMD64 FastCode:READY:AVX.

Код:
 ```
using var store = new CpX509Store(StoreName.My, StoreLocation.CurrentUser);
            store.Open(OpenFlags.OpenExistingOnly | OpenFlags.MaxAllowed);

            X509Certificate2Collection found = store.Certificates.Find(X509FindType.FindBySerialNumber,
serialNumber, false);
```

**Comment by Fasjeit** [comment]
Обновите CSP до последнего актуального релиза, как указано в readme.
Текущая версия 5.0.12600

**Comment by Poisent** [comment]
Спасибо. Сегодня попробуем. Отпишу по результатам.

**Comment by Poisent** [comment]
С последней версией всё заработало. Спасибо!
