### ISSUE TITLE
signedXml.CheckSignature() зависает.

### ISSUE THREAD

**Issue by Higen123** [CryptoPro/libcore#2]
При проверки подписи XML метод `CheckSignature()` зависает в случае, если подпись невалидна. Если подпись валидна, то метод отрабатывает корректно и возвращает `true`.

```csharp
static void Main(string[] args)
{
    var signed = new CmsSigner();
    LibCore.Initializer.Initialize();

    XmlDocument docWrong = new XmlDocument();
    docWrong.Load(@"C:\GetRequest(21.12.2022_20_09_30).xml");

    Console.WriteLine(ValidateXmlFIle(docWrong).ToString());
}
```
`ValidateXmlFIle` - метод из описания к libcore.

**Comment by Fasjeit** [comment]
Попробуйте последний релиз - ошибка должна уйти.
https://github.com/CryptoPro/libcore/releases/tag/v2023.1.23.1

**Comment by Higen123** [comment]
Работает! Спасибо!
