### ISSUE TITLE
Лицензирование бибилотеки

### ISSUE THREAD

**Issue by Bykiev** [CryptoPro/libcore#22]
Здравствуйте, прошло уже достаточно много времени, но до сих пор непонятно, как лицензируется библиотека. Наверное многих, кто внедряет библиотеку в свои проекты, интересует этот вопрос, т.к. если она будет платной, то нужно организовывать закупку, а это тоже время, которое нужно учитывать.

**Comment by Bykiev** [comment]
Спасибо, интересует именно использование на сервере. Закупать уже можно этот продукт?

**Comment by maxdm** [comment]
Закупать пока не получится, отпишу, когда будет готов прайс-лист.

**Comment by KozlovPavel677** [comment]
> Закупать пока не получится, отпишу, когда будет готов прайс-лист.

Здравствуйте.
У нас уже куплена серверная лицензия для 
КриптоПро.NET
она не подойдет ? Будет отдельная лицензия ?

**Comment by Bykiev** [comment]
> > Закупать пока не получится, отпишу, когда будет готов прайс-лист.
> 
> Здравствуйте. У нас уже куплена серверная лицензия для КриптоПро.NET она не подойдет ? Будет отдельная лицензия ?

Да, это будет другой продукт, с другими ценами

**Comment by KozlovPavel677** [comment]
> Да, это будет другой продукт, с другими ценами

Понял. 
Хорошо бы, если бы предусмотрели вариант с конвертацией лицензий (с возможной доплатой).

Зачем:
Текущий вариант КриптоПро .Net  (под Framework) - просто ужасен и использовать его невозможно. Слетает доступность ГОСТ алгоритмов почти при  каждом обновлении винды. Кого ни спрашивал из знакомых и коллег - все плюются и шлют проклятия.

Поэтому когда выкатили вариант под Net 6.0 который не слетает - мы были несказанно рады. Наконец-то сделали по-нормальному. Поэтому я рассматриваю вариант под Net 6.0 как удачную работу над ошибками (и платить полную цену заново за исправление нерабочего инструмента - это как-то перебор на мой взгляд)

Также в новостях было упомянуто что будет версия под Net 8.0 и сказали что рассматривается выпуск отдельной библиотеки без патча .Net. - Всеми руками ЗА! Это будет очень удобно. Одобряем.  (Возможно этот вариант сгодится не для всех сценариев, но нам достаточно. Мы просто подписываем XML и отправляем в ГИИС ДМДК. И думаю что таких как мы немало)

**Comment by Bykiev** [comment]
> Добрый день. В прайс-листе появилась позиция **Лицензия на право использования ПО "КриптоПро .NET" версии 2.0 на одном сервере** -- для использования libcore на сервере нужно приобретать именно эту лицензию. https://cryptopro.ru/order/OrderForm.aspx?catid=aa37ca5a-7cfc-e811-870f-0025900a9ce7 Позиции технической поддержки в этом же разделе. Для клиентских рабочих мест продукт не требует приобретения лицензии в отличии от версии для Framework.

Лицензию ведь нигде не надо будет прописывать в LibCore?

**Comment by maxdm** [comment]
Да, пока негде прописывать. Распечатать и положить рядом с сервером)
