### ISSUE TITLE
SignedCms signingCertificateV2 ("1.2.840.113549.1.9.16.2.47")

### ISSUE THREAD

**Issue by sk1nned** [CryptoPro/libcore#29]
Сейчас делаю SignedCms-подпись как в описании https://github.com/CryptoPro/libcore#signed-cms-detached
Но результат фактически разный получается если сравнивать - и по размеру и по содержимому.

Суть проблемы в том, что подпись, полученную через утилиту cptools сервис принимает, а через библиотеку - нет.

Тестирую на версии 2023.7.31.2 под виндой.

**Comment by Fasjeit** [comment]
Добрый день.

Скорее всего сервису-получателю не хватает атрибута `Pkcs9SigningTime`. 

Проставить его можно так:

```csharp
CmsSigner cmsSigner = new CmsSigner(gostCert);

// Добавляем время подписания в атрибуты
cmsSigner.SignedAttributes.Add(new Pkcs9SigningTime(DateTime.Now));

signedCms.ComputeSignature(cmsSigner);
```

Иначе можно сравнить декодированные asn1 сообщения, и посмотреть каких атрибутов не хватает.

**Comment by sk1nned** [comment]
Спасибо за наводку, сравнил декодированные сообщения - не хватает атрибута "1.2.840.113549.1.9.16.2.47", кажется это signingCertificateV2.
Как-то можно его добавить?

**Comment by sk1nned** [comment]
Pkcs9SigningTime пробовал добавлять - не помогает. И да, проверял, "1.2.840.113549.1.9.16.2.47" сам не добавляется.

**Comment by Fasjeit** [comment]
Видимо связано с https://github.com/CryptoPro/corefx/issues/41 (там же есть решение через Bouncy Castle).

Заметка для себя. Если делать нам - по подсмотреть сборку атрибута можно в
- [nuget](https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Packaging/Signing/Signatures/SigningCertificateV2.cs#L21) и [ещё](https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Packaging/Signing/Utility/AttributeUtility.cs#L251)
- [Rfc3161TimestampToken](https://github.com/dotnet/runtime/blob/e2a2bfff005ea0620cf1d2b04a01dc90bbfe8ead/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Rfc3161TimestampToken.cs#L571) - видимо в основном декодирование и проверка
- [TimestampTokenTests](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography.Pkcs/tests/Rfc3161/TimestampTokenTests.cs) - тут уже есть сборка руками

**Comment by sk1nned** [comment]
>Видимо связано с https://github.com/CryptoPro/corefx/issues/41 (там же есть решение через Bouncy Castle).

Сделал так - заработало.
Большое спасибо за помощь!

**Comment by maxdm** [comment]
> Видимо связано с [CryptoPro/corefx#41](https://github.com/CryptoPro/corefx/issues/41) (там же есть решение через Bouncy Castle).
> 
> Заметка для себя. Если делать нам - то подсмотреть сборку атрибута можно в
> 
> * [nuget](https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Packaging/Signing/Signatures/SigningCertificateV2.cs#L21) и [ещё](https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Packaging/Signing/Utility/AttributeUtility.cs#L251)
> * [Rfc3161TimestampToken](https://github.com/dotnet/runtime/blob/e2a2bfff005ea0620cf1d2b04a01dc90bbfe8ead/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Rfc3161TimestampToken.cs#L571) - видимо в основном декодирование и проверка
> * [TimestampTokenTests](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography.Pkcs/tests/Rfc3161/TimestampTokenTests.cs) - тут уже есть сборка руками

Точно, спасибо! Крутилось воспоминание об этом запросе в голове, но не смог вспомнить.
Магию в capilite мы с тех пор доделали. 
@Fasjeit, давай у нас в примере сделаем.

**Comment by sk1nned** [comment]
Проверил - атрибут добавляется, но сервис не принимает подпись.

**Comment by Fasjeit** [comment]
Была ошибка в порядке байт в серийном номере сертификата при кодировании - родной метод ms передаёт в Little-Endian, поэтому делаем Reverse перед записью. Теперь серийник сходится.

https://file.cryptopro.ru/f/igpJo7HGd8qjv21VDKiovVYsM0Yn5S3E/LibCore.Linux.2023.8.3.2.nupkg
https://file.cryptopro.ru/f/WU2SfxyHU31DRpXT8qwagxv3nlSLKbEH/LibCore.Windows.2023.8.3.2.nupkg

**Comment by sk1nned** [comment]
Да, сейчас всё ок.

**Comment by Fasjeit** [comment]
Отлично, спасибо.

Отставлю открытой, к сл. релизу допишу пример в Readme.
