### ISSUE TITLE
Поддержка проверки подписи S/MIME в MimeKit

### ISSUE THREAD

**Issue by Bykiev** [CryptoPro/libcore#31]
Здравствуйте, подскажите пожалуйста, возможно ли заставить работать проверку подписи в библиотеке [MimeKit](https://github.com/jstedfast/MimeKit)? При проверке ЭП выдает ошибку: "Failed to verify digital signature: Unknown algorithm '1.2.643.7.1.1.1.1'. ". Я попробовал посмотреть код и разобраться самостоятельно, но ничего подозрительного не нашел, в классе `WindowsSecureMimeDigitalSignature` в методе Verify вызывается `SignerInfo.CheckSignature`, но почему выпадает исключение - понять не могу....

https://github.com/jstedfast/MimeKit/blob/018fdc944b5331deb4fb2c267feb66362def75f1/MimeKit/Cryptography/WindowsSecureMimeDigitalSignature.cs#L201

LibCore инициализируется следующим образом:
`Initializer.Initialize(Initializer.DetouredAssembly.Xml | Initializer.DetouredAssembly.Pkcs);`

**Comment by Fasjeit** [comment]
Добрый день.

Если сделаете проект-пример, на котором можно будет комплектно воспроизвести - можем посмотреть.

**Comment by Bykiev** [comment]
Спасибо, постараюсь подготовить!

**Comment by Bykiev** [comment]
Оказалось, что проблема не в библиотеке, а в том, что инициализация LibCore происходила позже (перед вызовом app.Run()), чем запускалась задача Quartz, поэтому инициализацию надо делать прям первым вызовом. Спасибо!
