### ISSUE TITLE
Проблема при выполнении аутентификации по сертификату клиента на Kestrel на Linux

### ISSUE THREAD

**Issue by Chebura** [CryptoPro/libcore#32]
Добрый день. Я пытаюсь настроить сервер TLS на Kestrel (Linux), аналогично [issue](https://github.com/CryptoPro/libcore/issues/21), где коллега использует лицензию "TLS Server". Я тоже её получил, и TLS с серверным сертификатом GOST устанавливается успешно. Однако если включить принудительную аутентификацию по клиентскому сертификату ГОСТ, при попытке сделать хендшейк сервер выдаёт ошибку:

```
 Unhandled exception while processing 0HMT273ENSUKA.
      System.ComponentModel.Win32Exception (0x80090308): Unknown error -2146893048
         at System.Net.Security.CpSecureChannel.CreateFatalHandshakeAlertToken(SslPolicyErrors sslPolicyErrors, X509Chain chain)
         at System.Net.Security.CpSecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
         at LibCore.Net.Security.CpSslStream.CompleteHandshake(ProtocolToken& alertToken)
         at LibCore.Net.Security.CpSslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
```

Код сервера примерно такой:

```C#
public static void Main(string[] args)
		{
			var builder = WebApplication.CreateBuilder(args);

			builder.WebHost.UseKestrel(x =>
			{
				x.ConfigureHttpsDefaults(y =>
				{
					y.ServerCertificate = GetCert();
					y.ClientCertificateMode = Microsoft.AspNetCore.Server.Kestrel.Https.ClientCertificateMode.RequireCertificate;
					y.ClientCertificateValidation = (cert, chain, errors) =>
					{
						//Сюда не попадает
						return true;
					};
				});
			}).ConfigureLogging(x => x.AddConsole());


			builder.Services.AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme).AddCertificate(options =>
			{
				options.AllowedCertificateTypes = CertificateTypes.All;
				options.ValidateCertificateUse = false;
				options.ValidateValidityPeriod = false;
				options.Events = new CertificateAuthenticationEvents
				{
					OnCertificateValidated = context =>
					{
						//Сюда не попадает
						context.Success();
						return Task.CompletedTask;
					}
				};
			});

			builder.Services.AddAuthorization();

			var app = builder.Build();

			app.UseAuthentication();
			app.UseAuthorization();

			app.MapGet("/", () => "Hello World!");
		

			app.Run();

		}

		private static X509Certificate2 GetCert()
		{
			LibCore.Initializer.Initialize();
			return X509CertificateExtensions.Create("./gost.pfx", "12345678", CpX509KeyStorageFlags.CspNoPersistKeySet);
		}
```

Клиентская часть:
при попытке выполнять запросы из Яндекс.Браузера с поддержкой ГОСТ - выдаёт ту же ошибку установки соединения и сервер выписывает в лог ту же ошибку (см. выше). Аналогично при выполнении запроса через HttpClient:

```C#
var store = new X509Store("My", StoreLocation.CurrentUser);
	store.Open(OpenFlags.ReadOnly);
	cert = store.Certificates.Find(X509FindType.FindBySerialNumber, "7c000a90f90a0ce5ceb9049dee0003000a90f9", true).FirstOrDefault();
	
var url = new Uri("https://localhost:7028");

Console.WriteLine("Test mTls on {0}", url.ToString());

var handler = new HttpClientHandler();

if (cert != null)
	handler.ClientCertificates.Add(cert);

var client = new HttpClient(handler);

client.BaseAddress = url;
try
{
	var r = await client.GetAsync("");
	Console.WriteLine("Status: {0}", r.StatusCode);
	Console.WriteLine(await r.Content.ReadAsStringAsync());
}
catch (Exception e)
{
	Console.Error.WriteLine(e);
}
```

Запрос делаю из-под windows, клиентский серт грузится штатно, после чего соединение рвётся, на сервере та же ошибка, что выше.

У меня такой вопрос: лицензия "TLS Server" охватывает аутентификацию по сертификатам? Получается, что в режиме 

```
y.ClientCertificateMode = Microsoft.AspNetCore.Server.Kestrel.Https.ClientCertificateMode.RequireCertificate;
```

не работает. И в режиме allow с принудительной передачей клиентского сертификата ГОСТ тоже не работает.

**Comment by Chebura** [comment]
Проблема как-то сама собой решилась. Я проверил на тестовых стендах КриптоПро TLS с клиентским сертификатом и опытным путём выявил серт, который рабочий. С ним валидация клиентского сертификата на хендшейке проходит. Код сервера не поменялся.

```C#
x.ConfigureHttpsDefaults(y =>
				{
					y.ServerCertificate = GetCert();
					y.ClientCertificateMode = Microsoft.AspNetCore.Server.Kestrel.Https.ClientCertificateMode.RequireCertificate;
					y.ClientCertificateValidation = (certificate2, chain, arg3) =>
					{
						return true;
					};
				});
```

Цепочка доверия клиентского сертификата не валидируется, даже несмотря на то, что сам корневой сертификат Тестовый УЦ ООО "КРИПТО-ПРО" и в CustomTrustStore кладётся, и устанавливается на Linux через certmgr. Это вот я не очень понял, потому что на windows цепочка валидная. Но это как-бы не относится к ISSUE, хотя непонятно.

И ещё непонятно то что при попытке вот в такой конфигурации сервера сделать запрос с Яндекс.Браузере (с поддержкой КриптоПро и ГОСТ) браузер выдаёт ERR_SSL_VERSION_OR_CIPHER_MISMATCH. Если указать на сервере TLS 1.2, сервер рвёт соединение ERR_CONNECTION_CLOSED.

На сервере ошибка:

```
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
         at LibCore.Net.Security.CpSslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
```
При этом если клиентский сертификат не требовать - браузер работает корректно и показывает защищённое TLS-соединение. Мне не очень понятно, что тут происходит в момент хендшейка, потому что в ClientCertificateValidation не попадает и валится ещё до. 

А если делать запрос из HttpClient, то TLS с клиентским сертификатом работает нормально (за исключением валидации цепочки, о которой я писал выше, но это уже другая проблема).

**Comment by Fasjeit** [comment]
Добрый день.
###  "Цепочка доверия клиентского сертификата не валидируется, даже несмотря на то, что сам корневой сертификат Тестовый УЦ ООО "КРИПТО-ПРО" и в CustomTrustStore кладётся, и устанавливается на Linux через certmgr"

Как именно проверяется цепочка? Через `X509Chain` или через cptool\certmgr? Какая ошибка при проверке?

### "И ещё непонятно то что при попытке вот в такой конфигурации сервера сделать запрос с Яндекс.Браузере"
Для определения проблемы нам потребуются следующие данные

1 - полный стектрейс ошибки, включая `InnerException`.

2 - включить логирование tls в csp и прислать syslog
`sudo /opt/cprocsp/sbin/amd64/cpconfig -loglevel ssp -mask 0x1f`

(выключается следующей командой) - `sudo /opt/cprocsp/sbin/amd64/cpconfig -loglevel ssp -mask 0x01`

3 -  собрать pcap дамп, понятный wireshark при воспроизведении ошибки

4 - попробовать отключить сессии в csp
`sudo /opt/cprocsp/sbin/amd64/cpconfig -ini '\config\Parameters' -add long tls_max_sessions 0`

(включаются назад так) - `sudo /opt/cprocsp/sbin/amd64/cpconfig -ini '\config\Parameters' -add long tls_max_sessions 64`

**Comment by Chebura** [comment]
Пытался проверять цепочку двумя путями:
С указанием CustomTrustStore:

```C#
builder.Services.AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme).AddCertificate(options =>
			{
				options.CustomTrustStore.Add(new X509Certificate2("./root.cer"));
				options.ChainTrustValidationMode = X509ChainTrustMode.CustomRootTrust;
				options.RevocationMode = X509RevocationMode.NoCheck;
				options.AllowedCertificateTypes = CertificateTypes.All;
				options.ValidateCertificateUse = false;
				options.ValidateValidityPeriod = false;
				options.Events = new CertificateAuthenticationEvents
				{
					OnCertificateValidated = context =>
					{
						//Сюда не попадает
						context.Success();
						return Task.CompletedTask;
					}
				};
			});
```
и с указанием System:

```C#
builder.Services.AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme).AddCertificate(options =>
			{
				options.ChainTrustValidationMode = X509ChainTrustMode.System;
				options.RevocationMode = X509RevocationMode.NoCheck;
				options.AllowedCertificateTypes = CertificateTypes.All;
				options.ValidateCertificateUse = false;
				options.ValidateValidityPeriod = false;
				options.Events = new CertificateAuthenticationEvents
				{
					OnCertificateValidated = context =>
					{
						//Сюда не попадает
						context.Success();
						return Task.CompletedTask;
					}
				};
			});
```
Корневой серт во втором случае был импортирован через certmgr. Возможно я тут ошибся и нужно его ещё в трастед рут стор линукса подложить. Надо проверить. Но не суть. В обоих случаях на сервере пишется ошибка:

```
warn: Microsoft.AspNetCore.Authentication.Certificate.CertificateAuthenticationHandler[2]
      Certificate validation failed, subject was C=RU, S=Saint-Petersburg, L=Saint-Petersburg, O=Ekassir, OU=dev, CN=testclient, E=kalianovda@ekassir.com. UntrustedRoot A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
      
info: Microsoft.AspNetCore.Authentication.Certificate.CertificateAuthenticationHandler[7]
      Certificate was not authenticated. Failure message: Client certificate failed validation.
```

По поводу Яндекс.Браузера скину результат чуть позже.

**Comment by Chebura** [comment]
В общем я проверил цепочку доверия и она валится на рутовом серте.

```C#
var rootCa = LoadCert("./root.cer");
var client = LoadCert("./gost-client.cer");

var chain = X509Chain.Create();
chain.ChainPolicy.CustomTrustStore.Add(rootCa);
chain.ChainPolicy.TrustMode = X509ChainTrustMode.CustomRootTrust;
if (!chain.Build(client))
{
				Console.WriteLine("ERROR!"); // та же ошибка доверия, что указана выше
}
```

Честно говоря, я не очень понимаю, как проверять цепочку в таком случае? Может быть, корневой сертификат должен быть подгружен каким-то особым образом в CustomTrustStore?

**Comment by Fasjeit** [comment]
Можете приложить ваши сертификаты, на которых проверяете?

**Comment by Chebura** [comment]
> Можете приложить ваши сертификаты, на которых проверяете?

[examples.zip](https://github.com/CryptoPro/libcore/files/12418338/examples.zip)

**Comment by Fasjeit** [comment]
`TrustMode` и `CustomTrustStore` в настоящий момент не поддерживаются. Планируется переделка сборки с x509, после которой, я надеюсь, сможем с ними корректно работать.

Ваш сертификат установил в корневые
В win через оснастку сертификаты
В linux через

```bash
export PATH="$(/bin/ls -d /opt/cprocsp/{s,}bin/*|tr '\n' ':')$PATH"
certmgr -inst -store root -file ./root.cer
```

Выполняю построение цепочки через
```csharp
var client = new X509Certificate2(@"gost-client.cer");
var chain = X509Chain.Create();
chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;

if (!chain.Build(client))
{
    foreach (var r in chain.ChainStatus)
    {
        Console.Write(r.StatusInformation);
    }
}
```

Построение завершается успешно.

**Comment by Chebura** [comment]
> ```shell
> certmgr -inst -store root -file ./root.cer
> ```

Благодарю, вы правы. Делал установку под рутом, поэтому серт в сторе не находился. Повторил ту же операцию под учёткой процесса - и валидация прошла. То есть цепочка будет валидироваться только в режиме System, с использованием стора КриптоПро, так?

**Comment by Chebura** [comment]
С Яндекс.Браузером тоже разрешился вопрос, видимо не было доверия к выпущенному root.cer  сертификату сервера, в итоге он также смог аутентифицироваться успешно. Спасибо!

**Comment by Fasjeit** [comment]
Да, цепочки сейчас валидируются сейчас только на основе сторов csp.
