### ISSUE TITLE
X509Chain & X509ChainPolicy - CA-сертификат заданный в CustomTrustStore не влияет на валидацию

### ISSUE THREAD

**Issue by k0st1x** [CryptoPro/libcore#34]
Здравствуйте.
Имею сертификат, который загружаю с помощью
```cs
var certificate = X509CertificateExtensions.Create(data, password, CpX509KeyStorageFlags.CspNoPersistKeySet)
```
мне надо его проверить с помощью кода
```cs
using var chain = new X509Chain();
bool result = chain.Build(certificate);
```
У сертификата есть родительский CA-сертификат.
если я залью CA-сертификат в хранилище через
```bash
certmgr -inst -store uCA -file file.cer
```
То C#-код проходит валидацию.
Но нам надо как-то уйти от использования certmgr, чтобы работа была через API, тк сервис переносим в микросервис.
Поэтому надо поддерживать не реальное хранилище сертификатов, а импорт из корпоративного хранилища.
Пробую вот такой код:
```cs
var chainPolicy = new X509ChainPolicy { TrustMode = X509ChainTrustMode.CustomRootTrust };
chainPolicy.CustomTrustStore.AddRange(rootCertificates);
using var chain = new X509Chain { ChainPolicy = chainPolicy };
bool result = chain.Build(certificate);
```
результат получаю "false" с ошибкой невалидной цепочки.

Подскажите, как можно в C# коде подсунуть кастомные родительские сертификаты через API для использования X509Chain?

**Comment by Fasjeit** [comment]
Добрый день.

В настоящий момент поддерживаем построение цепочки только на основе хранилищ csp.

`CustomTrustStore` на текущий момент просто заглушка для реализации исходного интерфейса.

В ближайшее время планируется переделка всего что касается X509, в том числе планируем поддержать `CustomTrustStore`. Переделка глобальная, по срокам однозначно не могу пока что сказать.

Как только появится дополнительная информация - отпишусь тут.

#32

**Comment by Fasjeit** [comment]
Переоткрыл дабы не потерялась

**Comment by Fasjeit** [comment]
`TrustMode` и `CustomTrustStore` должны работать в текущей бете [LibCore 2024.2.29](https://github.com/CryptoPro/libcore/releases/tag/v2024.2.29).
