### ISSUE TITLE
EnvelopedCms Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException: "Неизвестный криптографический алгоритм."

### ISSUE THREAD

**Issue by Bykiev** [CryptoPro/libcore#35]
Здравствуйте, при шифровании возникает ошибка "Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException: "Неизвестный криптографический алгоритм."", сертификат ГОСТ (можно загрузить [отсюда](https://www.atsenergo.ru/sites/default/files/kriptoserver_ao_ats_2023.cer)), однако при установке переключателя `debugFlags: LibCore.Initializer.DebugFlags.DisableEnvelopedCmsDetours` шифрование выполняется без ошибки. В документации сказано, что его нужно устанавливать только когда одновременно используется ГОСТ и RSA, но в моем же случае используется только алгоритмы ГОСТ.

Код (в случае с флагом `DisableEnvelopedCmsDetours` вместо `EnvelopedCms` используется класс `CpEnvolpedCms`):

```
public static byte[] Encrypt(byte[] data, X509Certificate2 cert)
{
    var contentInfo = new ContentInfo(data);
    var envelopedCms = new EnvelopedCms(contentInfo);
    var recipient = new CmsRecipient(cert);
    envelopedCms.Encrypt(recipient);
    var encryptedBytes = envelopedCms.Encode();

    return encryptedBytes;
}
```

LibCore 2023.8.9.1
CSP: 5.0.12900

**Comment by Fasjeit** [comment]
Добрый день.

Была проблема, что ветвились по закрытому ключу. Если его не было - уходили в стандартное для `EnvelopedCms` поведение.

Теперь должны использовать открытый ключ. На win код выше заработал.

win - https://file.cryptopro.ru/f/Q6RQTrP0IB8ZfsrrYvMFjEOG0TQuGkdM/LibCore.Windows.2023.9.13.1.nupkg
linux - https://file.cryptopro.ru/f/SJr2UFB2I6nJyS6PzSIgLsyNkWEqYy2f/LibCore.Linux.2023.9.13.1.nupkg

**Comment by Bykiev** [comment]
Здравствуйте, спасибо, на Windows новая версия работает, на Linux пока нет возможности проверить. 
Вообще, есть ли разница использовать EnvelopedCms или CpEnvelopedCms без флага LibCore.Initializer.DebugFlags.DisableEnvelopedCmsDetours, если используются только алгоритм ГОСТ?

**Comment by Fasjeit** [comment]
В пределе разницы быть не должно. 

По факту `CpEnvelopedCms` теоретически должно быть надёжней, так как это честно реализованный класс, тогда как для `EnvelopedCms` используется слой магии, дабы заставить изначальных класс работать (т.е. больше мест, где возможны проблемы).

По сути того, что происходит де-факто при формировании cms - разницы нет.
