### ISSUE TITLE
s/mime - содержимое сообщения могло быть изменено на Astra Linux

### ISSUE THREAD

**Issue by Bykiev** [CryptoPro/libcore#41]
Здравствуйте, столкнулся с такой проблемой: при подписании s/mime на Windows ЭП проходит проверку без проблем, однако если подписать на Astra Linux (нет возможности протестировать другие ОС), то при проверке в outlook возникает ошибка:

> Ошибка: 
> Содержимое сообщения могло быть изменено.
> Подписано example@mail.ru с помощью ГОСТ Р 34.10-2012 256 бит/ГОСТ Р 34.11-2012 256 бит в 17:46:16 02.11.2023.

С чем может быть связана проблема? Сообщение представляет собой вложенный xml в кодировке Windows-1251, s/mime сообщение сначала подписывается (вычисляется открепленная подпись), а потом зашифровывается. Для отправки используется стандартный `SmtpClient`. В outlook сообщение расшифровывается корректно, но имеет проблему с подписью (зашифровываю и расшифровываю одним ключом).

**Upd** для шифрования используется класс `CpEnvelopedCms`

LibCore 2023.9.13.1
ОС: Astra Linux SE 1.7.4
.NET 6 (by AstraLinux Team)
CryptoPro CSP 5.0.12922 на Astra Linux, 5.0.12900 на Windows

**Comment by Bykiev** [comment]
Я провел несколько тестов и до шифрования если сохранить подпись, то подпись корректна, видимо она ломается уже при шифровании

**Comment by Bykiev** [comment]
Удалось найти проблему: во xml-вложение на Линуксе добавляются квадратные скобки:

На Линуксе:
`<!DOCTYPE message PUBLIC "SYSTEM" "message.dtd"[]>`

Исходный
`<!DOCTYPE message PUBLIC "SYSTEM" "message.dtd">`

Откуда берутся квадратные скобки?

**Comment by Bykiev** [comment]
Перепроверил на AstraLinux с CryptoPro CSP 5.0.12900 и .NET 6 от MS - это не влияет

**Comment by Fasjeit** [comment]
Добрый день.

1. Для начала стоит проверить (если ещё нет), что ваш сценарий работает корректно на RSA + чистом (без libcore) дотнете.

2. Также стоит проверить, проверяется ли сама подпись при проверке в коде (т.е. позвать расшифрование + проверку в дотнете). Т.е. подписать + зашифровать данные (как для smtp), перенести на целевую машину, проверить там.

3. Если на RSA не воспроизводится - то нам, как и прежде, понадобится комплектный пример по формированию и отправке smtp сообщения. Если для пункта 2 тоже воспроизводите ошибку - понадобится и пример для него.

**Comment by Bykiev** [comment]
> Добрый день.
> 
> 1. Для начала стоит проверить (если ещё нет), что ваш сценарий работает корректно на RSA + чистом (без libcore) дотнете.
> 2. Также стоит проверить, проверяется ли сама подпись при проверке в коде (т.е. позвать расшифрование + проверку в дотнете). Т.е. подписать + зашифровать данные (как для smtp), перенести на целевую машину, проверить там.
> 3. Если на RSA не воспроизводится - то нам, как и прежде, понадобится комплектный пример по формированию и отправке smtp сообщения. Если для пункта 2 тоже воспроизводите ошибку - понадобится и пример для него.

Спасибо, т.е. это все проверить на Linux надо? Т.к. этот же код полностью работает на Windows.

**Comment by Fasjeit** [comment]
Если проблемное сообщение формируется на Linux - то проверить нужно именно там.

**Comment by Bykiev** [comment]
> Если проблемное сообщение формируется на Linux - то проверить нужно именно там.

на тестовом УЦ КриптоПро нашел только генерация сертификатов по ГОСТ, можно ли там сгенерировать RSA-сертификат?

**Comment by Fasjeit** [comment]
https://file.cryptopro.ru/f/OEneUw4O3QkZxb9MEWVNOR40yFoJE68P/temp.zip
Архив с сертификатами (rsa + корневой rsa).

пароля на архив и сертификаты **НЕТ** (т.е. пустая строка для pfx).

**Comment by Bykiev** [comment]
> https://file.cryptopro.ru/f/OEneUw4O3QkZxb9MEWVNOR40yFoJE68P/temp.zip Архив с сертификатами (rsa + корневой rsa).
> 
> пароля на архив и сертификаты **НЕТ** (т.е. пустая строка для pfx).

А как правильно установить его? Автоматически устанавливается в хранилище Другие пользователи, но с закрытым ключом не сопоставляется

**Comment by Fasjeit** [comment]
Если хотим тестировать RSA без libcore сертификаты необходимо устанавливать в родное хранилище дотнета, например через [dotnet-certificate-tool](https://github.com/gsoft-inc/dotnet-certificate-tool)

**Comment by Bykiev** [comment]
> Если хотим тестировать RSA без libcore сертификаты необходимо устанавливать в родное хранилище дотнета, например через [dotnet-certificate-tool](https://github.com/gsoft-inc/dotnet-certificate-tool)

Ничего не изменилось, dotnet-certificate-tool написал, что сертификат был установлен в хранилище Личное текущего пользователя. При попытке подписи в приложении ошибка:

```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Ключ не существует.
   at Internal.Cryptography.CngCommon.TrySignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, Span`1 signature, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32& bytesWritten)
   at System.Security.Cryptography.RSACng.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Int32& bytesWritten)
   at System.Security.Cryptography.Pkcs.CmsSignature.RSAPkcs1CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& signatureAlgorithm, Byte[]& signatureValue)
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
```

**Comment by Bykiev** [comment]
Похоже, что проблема из-за того, что в Linux/Windows символы новой строки разные

**Comment by Bykiev** [comment]
https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html
