### ISSUE TITLE
[Вопрос] Добавление сертификата из pfx в CpX509Store (My, CurrentUser) под Linux

### ISSUE THREAD

**Issue by kae** [CryptoPro/libcore#46]
Пытаюсь реализовать добавление загруженного сертификата в pfx формате в локальное хранилище.

Получение `X509Certificate2` из бинарника (на основании примера) проходит успешно.

Показывает, что закрытый ключ доступен и даже `ToString()` даёт `LibCore.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider`
В консоли при этом отображается  `<csp>CPCImportKey!License fail cc=0x7fafb008e220` но на функциональность вроде бы не влияет.

После вызова `.Add()` на объекте хранилища, сертификат добавляется, но закрытого ключа нет.

Логика подсказывает, что `CspNoPersistKeySet` связан с тем, что контейнер не создаётся и не импортируется.

Но самостоятельные попытки перебирать другие варианты наборов флагов приводят либо к ошибке создания сертификата, либо к сертификату в хранилище без закрытого ключа.

Есть что-то, что я упускаю или функциональность в библиотеке/под Linux не поддерживается через .NET?

@Fasjeit

**Comment by kae** [comment]
С набором ключей 

`LibCore.Security.Cryptography.X509Certificates.CpX509KeyStorageFlags.UserKeySet | LibCore.Security.Cryptography.X509Certificates.CpX509KeyStorageFlags.Exportable
				| LibCore.Security.Cryptography.X509Certificates.CpX509KeyStorageFlags.PersistKeySet`

и запуске приложения в интерактивной консоли добавление прошло успешно, но прерывалось запросом пароля к контейнеру.

С высокой вероятностью ошибки при работе в виде сервиса связаны именно с невозможностью получить интерактивный ввод от пользователя.

Есть ли возможность указать заранее "пустой" пароль, либо в принципе отменить запрос пароля?

**Comment by maxdm** [comment]
Когда я смотрел поддержку флагов в .NET 7 лет назад — поддержки silent не было и единственным вариантом было использовать p/invoke.
https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=72898#post72898

9 дек. 2023 г., в 14:58, Andrey Kuznetsov ***@***.***> написал(а):

﻿

С набором ключей

LibCore.Security.Cryptography.X509Certificates.CpX509KeyStorageFlags.UserKeySet | LibCore.Security.Cryptography.X509Certificates.CpX509KeyStorageFlags.Exportable | LibCore.Security.Cryptography.X509Certificates.CpX509KeyStorageFlags.PersistKeySet

и запуске приложения в интерактивной консоли добавление прошло успешно, но прерывалось запросом пароля к контейнеру.

С высокой вероятностью ошибки при работе в виде сервиса связаны именно с невозможностью получить интерактивный ввод от пользователя.

Есть ли возможность указать заранее "пустой" пароль, либо в принципе отменить запрос пароля?

**Comment by kae** [comment]
Из обсуждения по ссылке не смог осознать что именно у себя через P/Invoke и где вызывать?

`LibCore.Security.Cryptography.X509Certificates.X509CertificateExtensions.Create` заменить на вариацию `public static X509Certificate2[] Read(string filename, string password)` из обсуждения?

**Comment by Fasjeit** [comment]
Интерфейс X509Store и X509Certificate2 не позволяет указать имя контейнера при импорте PFX, поэтому для ГОСТа всегда будет отображаться окно выбора носителя и имени контейнера.

Расширение интерфейса требует реализации копирования контейнера для его установки.

Реализация данного интерфейса в libcore есть в планах, но не в ближайших. Пока сосредоточены на переходе на 8.0.

**Comment by kae** [comment]
Поддержку .NET 8 очень ожидаем!

Пока обошёлся костылём с сохранением сертификата во временный файл и вызовом certmgr из процесса сервиса.
