### ISSUE TITLE
LibCore зависит от уязвимых версий пакетов

### ISSUE THREAD

**Issue by Bykiev** [CryptoPro/libcore#47]
Здравствуйте, LibCore содержит транзитивные зависимости на уязвимые библиотеки `System.Security.Cryptography.Pkcs` 6.0.0 и `System.Security.Cryptography.Xml` 6.0.0. Можно ли обновить их на стороне LibCore?

**Comment by Fasjeit** [comment]
В ближайшее время подготовим релиз для 6.0 с обновлёнными зависимостями.

**Comment by Fasjeit** [comment]
Текущие сборки для тестов с обновлёнными пакетами.

https://file.cryptopro.ru/f/WSxnzwhFS8fT2hiOWFGHqLCywtfOoMsI/LibCore.Linux.2024.1.10.1.nupkg
https://file.cryptopro.ru/f/DwsMD13lwGsLDBxWcwOU6JPHKbMN0fC0/LibCore.Windows.2024.1.10.1.nupkg

**Comment by Vanwards** [comment]
> Текущие сборки для тестов с обновлёнными пакетами.
> 
> https://file.cryptopro.ru/f/WSxnzwhFS8fT2hiOWFGHqLCywtfOoMsI/LibCore.Linux.2024.1.10.1.nupkg https://file.cryptopro.ru/f/DwsMD13lwGsLDBxWcwOU6JPHKbMN0fC0/LibCore.Windows.2024.1.10.1.nupkg

Подскажите пожалуйста, а в эту сборку кроме обновления зависимостей вошло что-то еще, чего нет в релизах?
У меня есть просьба - по возможности где-то публиковать свод изменений в библиотеках, можно в очень кратком виде, типа changelog.

**Comment by Fasjeit** [comment]
Изменений кроме обновления версий зависимостей нет.
