### ISSUE TITLE
'Не удалось подписать документ. Код ошибки: -532462766. Текст ошибки: Unhandled exception. LibCore.Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Provider could not perform the action since the context was acquired as silent.

### ISSUE THREAD

**Issue by KozlovPavel677** [CryptoPro/libcore#48]
Добрый день.

Ранее была ошибка 
https://github.com/CryptoPro/libcore/issues/33
Повторилась снова для другого юрлица / токена.

Попробовали тот же рецепт.
Попросил админов запомнить там пароль, они попробовали, но к сожалению КриптоПро не выдал запрос на пароль, поэтому запомнить его не удалось. И выдается указанная ошибка "Provider could not perform the action since the context was acquired as silent.".

Не подскажете почему такое возможно ?
Можно как-то самим впихнуть этот пароль в хранилище, миную КриптоПро ?
Или заставить крипто про задать этот вопрос. Прочему он не спрашивает пароль ?

**Comment by Bykiev** [comment]
Здравствуйте, в Инструментах КриптоПро (cptools) нажмите кнопку "Показать расширенные" во вкладке Настройки будет кнопка "Удалить сохраненные пароли". Запрос на пароль появится в любой момент при попытке получения доступа к ЭП, например, при тестировании контейнера или шифровании/подписи.

**Comment by Fasjeit** [comment]
Добрый день.

Программно пин-код на контейнер ключа можно указать используя метод `SetContainerPassword(...)` для объектов типа `Gost_xxx_CryptoServiceProvider`. Вызывать этот метод нужно до первого обращения к ключу.

Т.е. последовательность действий такая.
1. Получаем объект криптопровайдера для закрытого ключа.
2. Вызываем метод `SetContainerPassword`, передавая ему корректный пин для контейнера ключа.
3. Используем объект криптопровайдера для осуществления криптографических операций.

Проверка корректности переданного пин-кода будет производиться только в момент обращения к ключу (т.е. на шаге 3.).

**Comment by KozlovPavel677** [comment]
Спасибо за помощь.
Кнопка "Удалить сохраненные пароли" помогает, но нам не совсем подошла, так как сбрасывает пароли для всех контейнеров а нужно было только для одного.
Тогда мы кнопкой "Сменить пароль контейнера" поменяли пароль со старого на новый но такой же. т.е. пароль не поменялся но зато КриптоПро стал спрашивать пароль при попытке получения доступа и мы смогли его ввести и сохранить и все заработало.
