### ISSUE TITLE
CertDuplicateCertificateContext!failed

### ISSUE THREAD

**Issue by Bykiev** [CryptoPro/libcore#49]
Здравствуйте, на Astra Linux SE в журнале постоянно ошибки:

```
<capi20>pfx_FillPfxContextFromBlob!() asn1D_PFX failed
<capi20>CertDuplicateCertificateContext!failed: LastError = 0x57
<capi20>CertDuplicateCertificateContext!failed: LastError = 0x57
<capi20>CertDuplicateCertificateContext!failed: LastError = 0x57
```
Предполагаю, что такая проблема может быть из-за того, что на сервере размещено несколько приложений, использующих LibCore. Можно ли как-то решить эту проблему?

LibCore 2024.1.10.1
Astra Linux SE 1.7

**Comment by Fasjeit** [comment]
Добрый день.

Уточните пожалуйста версию csp.

Есть ли возможность узнать, какие именно операции (подпись, получение сертификата, прочее) выполняются при возникновении данных ошибок?

Влияет ли возникновение данных ошибок на функционирование приложений?

"Предполагаю, что такая проблема может быть из-за того, что на сервере размещено несколько приложений, использующих LibCore." - т.е. данная ошибка воспроизводится на фиксированной машине только при работе нескольких приложений?

**Comment by Bykiev** [comment]
Здравствуйте, версия CSP - 5.0.12922. 

> Есть ли возможность узнать, какие именно операции (подпись, получение сертификата, прочее) выполняются при возникновении данных ошибок?

Попробуем установить, какая операция вызывает эту ошибку, но потребуется некоторое время

> Влияет ли возникновение данных ошибок на функционирование приложений?

Нет, все приложения работают корректно, только записи в логах

> "Предполагаю, что такая проблема может быть из-за того, что на сервере размещено несколько приложений, использующих LibCore." - т.е. данная ошибка воспроизводится на фиксированной машине только при работе нескольких приложений?

Пока подтвердить эту теорию не могу, не помню, были ли записи `CertDuplicateCertificateContext!failed` до публикации нескольких приложения, попробуем развернуть на другом сервере

**Comment by Bykiev** [comment]
Удалось выяснить, что проблема возникает во время подписи

**Comment by Bykiev** [comment]
@Fasjeit, может быть есть какие-то логи CSP в ОС и они как-то помогут в поиске проблемы?

**Comment by yodasad** [comment]
Добрый день!

Подскажите, данные записи в логе появляются в результате вызова конкретного участка кода в Вашем приложении?
Сможете предоставить пример минимального кода, при выполнении которого возникают данные записи?

Включите подробное логирование для модулей cаpai10 и capi20:

 sudo /opt/cprocsp/sbin/amd64/cpconfig -loglevel capi10 -mask 0x3f
 sudo /opt/cprocsp/sbin/amd64/cpconfig -loglevel capi20 -mask 0x3f

Посмотреть текущий уровень:
sudo /opt/cprocsp/sbin/amd64/cpconfig -loglevel capi10 -view
sudo /opt/cprocsp/sbin/amd64/cpconfig -loglevel capi20 -view

**Comment by Bykiev** [comment]
@yodasad, здравствуйте! Включение подробного логирования ничего не изменило, новых записей в syslog нет.

Наш код полностью повторяет пример [SignedXml ](https://github.com/CryptoPro/libcore?tab=readme-ov-file#-signedxml)

**Comment by yodasad** [comment]
> новых записей в syslog нет.
Это очень странно. Какая редакция CSP? KC1 или KC2?
Если KC2, то попробуйте после изменения настроек логирования перезапустить службу cprocsp, а затем своё приложение.
Приложение после изменения настроек логирования CSP перезапускали?
Пришлите получившийся лог syslog.

> Наш код полностью повторяет пример [SignedXml ](https://github.com/CryptoPro/libcore?tab=readme-ov-file#-signedxml)
Это хорошо. Соберите, пожалуйста, минимальный консольный пример с этим кодом и если на нём воспроизводится поведение, присылайте ссылку на репозиторий с примером, попробуем воспроизвести у себя.

**Comment by Bykiev** [comment]
Довольно сложно определить проблему, пока удалось установить, что тип проекта никак не влияет. Под подозрением wcf-клиент (добавлена ссылка на WCF-службу), больше пока не знаю, на что думать.

**Comment by Bykiev** [comment]
Итак, первые результаты: 
`<capi20>pfx_FillPfxContextFromBlob!() asn1D_PFX failed`
возникает при проверке подписи в сообщении с помощью MailKit, при этом проверка проходит успешно. Проверка осуществляется следующим образом:

```
using (var msg = await inbox.GetMessageAsync(message))
{
    if (msg != null)
    {
        var sign = msg.Body as MultipartSigned;
        if (sign != null)
        {
            using (var ctx = new WindowsSecureMimeContext())
            {
                foreach (var signature in await sign.VerifyAsync(ctx))
                {
                   bool valid = signature.Verify();
                }
            }
        }
    }
}
```

**Comment by yodasad** [comment]
`<capi20>pfx_FillPfxContextFromBlob!() asn1D_PFX failed`
Это ошибка должна уйти в будущих версиях CSP, она связана с паразитными записями, возникающими в результате работы функции CryptQueryObject(...), выполняющей разбор блоба с сертификатом.

**Comment by yodasad** [comment]
> Довольно сложно определить проблему, пока удалось установить, что тип проекта никак не влияет. Под подозрением wcf-клиент (добавлена ссылка на WCF-службу), больше пока не знаю, на что думать.

Проанализируйте внимательно код загрузки и поиска сертификата (из хранилища, из PFX), есть ли использования конструктора сертификата, принимающего на вход `IntPtr`.

**Comment by Bykiev** [comment]
> > Довольно сложно определить проблему, пока удалось установить, что тип проекта никак не влияет. Под подозрением wcf-клиент (добавлена ссылка на WCF-службу), больше пока не знаю, на что думать.
> 
> Проанализируйте внимательно код загрузки и поиска сертификата (из хранилища, из PFX), есть ли использования конструктора сертификата, принимающего на вход `IntPtr`.

Сертификат мы ищем сами:

 ```
public static X509Certificate2? FindByThumbprint(string thumbprint, StoreName storeName, StoreLocation storeLocation)
        {
            ServicePointManager.ServerCertificateValidationCallback = delegate
            {
                return true;
            };

            bool isWindows = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
            if (isWindows)
            {
                using (var store = new X509Store(storeName, storeLocation))
                {
                    store.Open(OpenFlags.ReadOnly);
                    var certificates = store.Certificates.Cast<X509Certificate2>().ToList();
                    return certificates.FirstOrDefault(d => d.Thumbprint == thumbprint);
                }
            }
            else
            {
                using (var store = new CpX509Store(storeName, storeLocation))
                {
                    store.Open(OpenFlags.ReadOnly);
                    var certificates = store.Certificates.Cast<X509Certificate2>().ToList();
                    return certificates.FirstOrDefault(d => d.Thumbprint == thumbprint);
                }
            }
        }
```

Что бы было проще найти источник ошибки, чисто теоретически, что может вызывать такую ошибку в логе?

**Comment by Bykiev** [comment]
> > Довольно сложно определить проблему, пока удалось установить, что тип проекта никак не влияет. Под подозрением wcf-клиент (добавлена ссылка на WCF-службу), больше пока не знаю, на что думать.
> 
> Проанализируйте внимательно код загрузки и поиска сертификата (из хранилища, из PFX), есть ли использования конструктора сертификата, принимающего на вход `IntPtr`.

Теоретически, такие вызовы есть здесь?
https://github.com/search?q=repo%3Adotnet%2Fwcf+new+X509Certificate2%28&type=code

**Comment by Bykiev** [comment]
@yodasad, ошибка `<capi20>CertDuplicateCertificateContext!failed: LastError = 0x57` действительно возникает при вызове метода WCF-службы. Если нужен пример, то могу куда-то отправить лично, не через Github.

`binding.Security.Mode = BasicHttpSecurityMode.Transport;`

**Comment by Bykiev** [comment]
@yodasad, в консольном приложении ошибка другая:

```
Feb  9 10:50:19 AstraTest dotnet[16210]: <ssp>AddToMessageLog!CryptoPro TLS. Connection alert accepted 0x28
Feb  9 10:50:19 AstraTest dotnet[16210]: <ssp>InitializeSecurityContextW!(failed: 0xFFFFFFFF80090326, phCredential = 0x7ee8b77fbef8, phContext = 0x7ee8b77fbee0)
```

**Comment by Bykiev** [comment]
@Fasjeit, @yodasad, нужна ли еще какая-то дополнительная информация от меня для изучения проблемы?

**Comment by yodasad** [comment]
@Bykiev , если есть готовый пример, который воспроизводит проблему, то присылайте.
Можно передать через наш [Файлообменный сервис](https://file.cryptopro.ru/)

**Comment by yodasad** [comment]
Извиняюсь, неправильная ссылка
https://upload.cryptopro.ru
Имя пользователя: uoiwdyj
Пароль: tdjycvz

**Comment by Bykiev** [comment]
> Извиняюсь, неправильная ссылка https://upload.cryptopro.ru Имя пользователя: uoiwdyj Пароль: tdjycvz

Загрузил архив ConsoleApp111.zip

**Comment by yodasad** [comment]
Пришлите, пожалуйста, ссылку на загруженный файл.

**Comment by Bykiev** [comment]
https://upload.cryptopro.ru/f/7LaeawtMV6rPD1tQ0Jabin5kV5ZwdMDH/ConsoleApp111.zip

**Comment by Bykiev** [comment]
@yodasad, вам удалось воспроизвести ошибку?

**Comment by yodasad** [comment]
Да, поведение воспроизвели. Проблема с WCF клиентом, в приложении не хватало установки детура для TLS, поэтому в Вашем случае правильно инициализировать библиотеку через вызов `LibCore.Initializer.Initialize()`. Но далее возникает проблема с TLS подключением к веб-сервису, причины пока не ясны, разбираемся.

**Comment by yodasad** [comment]
На этом сервере (gwkits.odusv.so-ups.ru) используются специфичные TLS-сюиты, для их поддержки выполните следующую настройку:

```
sudo /opt/cprocsp/sbin/amd64/cpconfig -ini '\config\parameters' -add long tls_client_disable_rsa_key_exchange 0
```

**Comment by Bykiev** [comment]
Спасибо, такая ошибка ушла, теперь другая:

```
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertEnumCertificatesInStore (hCertStore = 0x76774c0384c0, pPrevCertContext = 0x76774c043d18)
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertFindCertificateInStore (hCertStore = 0x76774c0384c0, dwCertEncodingType = 65537, dwFindFlags = 0x00000000, dwFindType = 0, pvFindPara = (nil), pPrevCertContext = 0x76774c043d18)
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertFindCertificateInStore returned: pCertContext = 0x76774c02d018
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertEnumCertificatesInStore (returned: pCertContext = 0x76774c02d018)
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertDuplicateCertificateContext (pCertContext = 0x76774c02d018)
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertDuplicateCertificateContext returned: pCertContext = 0x76774c02d018
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertGetCertificateContextProperty (pCertContext = 0x76774c02d018, dwPropId = 125, pcbData = 0x767770b06e28)
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertGetCertificateContextProperty failed: LastError = 0x80092004
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertFreeCertificateContext (pCertContext = 0x76774c02d018)
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertFreeCertificateContext returned
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertEnumCertificatesInStore (hCertStore = 0x76774c0384c0, pPrevCertContext = 0x76774c02d018)
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertFindCertificateInStore (hCertStore = 0x76774c0384c0, dwCertEncodingType = 65537, dwFindFlags = 0x00000000, dwFindType = 0, pvFindPara = (nil), pPrevCertContext = 0x76774c02d018)
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertFindCertificateInStore failed: LastError = 0x80092004
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertEnumCertificatesInStore (failed: LastError = 0x80092004)
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertFreeCertificateContext (pCertContext = 0x76774c02d018)
Feb 13 12:50:01 AstraTest dotnet[24910]: <capi20>CertFreeCertificateContext returned

```

**Comment by Bykiev** [comment]
> На этом сервере (gwkits.odusv.so-ups.ru) используются специфичные TLS-сюиты, для их поддержки выполните следующую настройку:
> 
> ```
> sudo /opt/cprocsp/sbin/amd64/cpconfig -ini '\config\parameters' -add long tls_client_disable_rsa_key_exchange 0
> ```

Кстати, это изменение было сделано в версии [5.0.12800 ](https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=140818#post140818)

> tls: Отключены TLS-сюиты, использующие RSA Key Exchange. Для включения: tls_server_disable_rsa_key_exchange = 0, tls_client_disable_rsa_key_exchange = 0 (CPCSP-13512).

Как только обычным людям понять, что нужно было его включить?

**Comment by yodasad** [comment]
> Спасибо, такая ошибка ушла, теперь другая:
> 

Отключите диагностическое логирование:
```
cp@dss-astra-se16:~/tmp/github$ sudo /opt/cprocsp/sbin/amd64/cpconfig -loglevel capi10 -mask 0x01
cp@dss-astra-se16:~/tmp/github$ sudo /opt/cprocsp/sbin/amd64/cpconfig -loglevel capi20 -mask 0x01
```

**Comment by Bykiev** [comment]
Тогда вроде все, проблему можно закрывать. Спасибо Вам большое за помощь!

**Comment by Bykiev** [comment]
@yodasad, при инициализации без параметров LibCore на сервере, где нет сертификатов, стала возникать ошибка: "Не удалось установить отношения доверия для защищенного калана SSL/TLS с полномочиями"

хотя в коде игнорируется:

```
client.ClientCredentials.ServiceCertificate.SslCertificateAuthentication =
    new X509ServiceCertificateAuthentication()
    {
        CertificateValidationMode = X509CertificateValidationMode.None,
        RevocationMode = X509RevocationMode.NoCheck
    };
```

Не подскажете, почему так происходит?

**Comment by Bykiev** [comment]
@yodasad, здравствуйте, не поможете снова?

**Comment by Bykiev** [comment]
Результат подключения curl с этого сервера:

```
/opt/cprocsp/bin/amd64/curl -v https://gwkits.odusv.so-ups.ru/kits/gw/http/svl
*   Trying 178.74.160.15:443...
* TCP_NODELAY set
* Connected to gwkits.odusv.so-ups.ru (178.74.160.15) port 443 (#0)
* schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
* Closing connection 0
* schannel: shutting down SSL/TLS connection with gwkits.odusv.so-ups.ru port 443
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
admtandem@sr-tehno-skr-t:~/Desktops/Desktop1/testCert2$
```

**Comment by Bykiev** [comment]
Результат выполнения curl на этом сервере:
```
/opt/cprocsp/bin/amd64/curl -v https://gwkits.odusv.so-ups.ru/kits/gw/http/svl
*   Trying 178.74.160.15:443...
* TCP_NODELAY set
* Connected to gwkits.odusv.so-ups.ru (178.74.160.15) port 443 (#0)
* schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
* Closing connection 0
* schannel: shutting down SSL/TLS connection with gwkits.odusv.so-ups.ru port 443
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
```

**Comment by yodasad** [comment]
Добрый день!

По логу похоже на прежнюю проблему с RSA-сюитами.

```
sudo /opt/cprocsp/sbin/amd64/cpconfig -ini '\config\parameters\tls_client_disable_rsa_key_exchange' -view
```
Что выводит?

У Вас CSP КС1 или КС2 на этом сервере? Если КС2, то после изменения параметра нужно перезапустить службу `cprocsp`.

**Comment by Bykiev** [comment]
> Добрый день!
> 
> По логу похоже на прежнюю проблему с RSA-сюитами.
> 
> ```
> sudo /opt/cprocsp/sbin/amd64/cpconfig -ini '\config\parameters\tls_client_disable_rsa_key_exchange' -view
> ```
> 
> Что выводит?
> 
> У Вас CSP КС1 или КС2 на этом сервере? Если КС2, то после изменения параметра нужно перезапустить службу `cprocsp`.

Здравствуйте! CSP КС1

`sudo /opt/cprocsp/sbin/amd64/cpconfig -ini '\config\parameters\tls_client_disable_rsa_key_exchange' -view`
выдает 0

**Comment by Bykiev** [comment]
Что интересно, выполнил следующую команду на этом сервере:
`openssl s_client -connect gwkits.odusv.so-ups.ru:443 -showcerts`

```
SSL handshake has read 3690 bytes and written 648 bytes
Verification error: self signed certificate in certificate chain
---
New, TLSv1.2, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: CBF282D89BD207FB2BBE3ECCE99A60A1EA112006453FD54FFC3B0BBF56BD54CC
    Session-ID-ctx:
    Master-Key: 8BA048C5FC577CBCC5235047922C6765CB6221B73B1C9D3575EBF1E475FBF0810EE4EBE2D8DC3D988ADAFD1327281B2C
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1708335776
    Timeout   : 7200 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
    Extended master secret: no
```
На том сервере, где работает, команда вообще не выполняется (ничего не происходит). Не совсем понимаю, что это может значить... Версии OpenSSL одинаковые (1.1.1n).

**Comment by maxdm** [comment]
Правильно. Можно и там
Приложите пожалуйста tcpdump попытки подключения  с первого и второго сервера.
Плюс вывод команды csptest -tlsc -server имя_хоста -v
Версии КриптоПоо CSP одинаковые?


19 февр. 2024 г., в 19:46, Andrey Bykiev ***@***.***> написал(а):

﻿

@yodasad<https://github.com/yodasad>, я ведь правильно понимаю, что проблема не связана с LibCore и .NET, а дело уже с CSP? Может нам лучше создать заявку на support.cryptopro.ru, ведь у нас есть лицензия и сертификат поддержки серверной версии?
