### ISSUE TITLE
Открепленная подпись не проходит проверку в ЕСИА

### ISSUE THREAD

**Issue by SergeyKobyakov** [CryptoPro/libcore#5]
Использую версию пакета под windows, последний релиз. КриптоПро 5.0.12600 КС1. 
Открепленная подпись формируется, но в ЕСИА проверку не проходит 
```json
{"code":"ESIA-005002","message":"Некорректная подпись"}
```

Сделал минимальный проект для примера.
[Signer.zip](https://github.com/CryptoPro/libcore/files/10682624/Signer.zip)

Тот же код из .Net 4.7.2 подписывает корректно.

**Comment by Fasjeit** [comment]
Для тестов убрали кодирование подписи при записи в txt и сделали явную запись данных и подписи в файл.

```csharp
File.WriteAllBytes("data.txt",
    bytes);
File.WriteAllBytes("data.sig",
    signature);
```

То полученная результирующая подпись с данным файлом успешно проходит проверку подписи на госулугах (электронного документа. ЭП — отсоединенная, в формате PKCS#7, https://www.gosuslugi.ru/pgu/eds/order).
![изображение](https://user-images.githubusercontent.com/15075638/217470098-77bd1c34-19bc-44f2-900e-c289f340c9fe.png)

Как именно вы проверяете корректность полученной вами подписи? В каком формате передаются данные и подпись?

**Comment by SergeyKobyakov** [comment]
Подпись, после конвертации в Base64 и замены некоторых символов, передаю в запросе к ЕСИА на получение токена доступа. Подписывает она uuid ee34f56f-48c9-4a74-87c1-addcda61df38, который передается в запросе.
 
https://esia-portal1.test.gosuslugi.ru/esia-rs/api/public/v1/orgs/ext-app/ee34f56f-48c9-4a74-87c1-addcda61df38/tkn?signature=MIIUHwYJKoZIhvcNAQcCoIIUEDCCFAwCAQExDDAKBggqhQMHAQECAjALBgkqhkiG9w0BBwGgghHmMIIICTCCB7agAwIBAgIKNGUnwwAAAAAG0zAKBggqhQMHAQEDAjCCATsxITAfBgkqhkiG9w0BCQEWEmRpdEBkaWdpdGFsLmdvdi5ydTELMAkGA1UEBhMCUlUxGDAWBgNVBAgMDzc3INCc0L7RgdC60LLQsDEZMBcGA1UEBwwQ0LMuINCc0L7RgdC60LLQsDFTMFEGA1UECQxK0J_RgNC10YHQvdC10L3RgdC60LDRjyDQvdCw0LHQtdGA0LXQttC90LDRjywg0LTQvtC8IDEwLCDRgdGC0YDQvtC10L3QuNC1IDIxJjAkBgNVBAoMHdCc0LjQvdGG0LjRhNGA0Ysg0KDQvtGB0YHQuNC4MRgwFgYFKoUDZAESDTEwNDc3MDIwMjY3MDExFTATBgUqhQNkBBIKNzcxMDQ3NDM3NTEmMCQGA1UEAwwd0JzQuNC90YbQuNGE0YDRiyDQoNC-0YHRgdC40LgwHhcNMjIxMDMxMTI1NTAxWhcNMzcxMDMxMTI1NTAxWjCCAYQxFTATBgUqhQNkBBIKNjY2MzAwMzEyNzEeMBwGCSqGSIb3DQEJARYPY2FAc2tia29udHVyLnJ1MRgwFgYFKoUDZAESDTEwMjY2MDU2MDY2MjAxCzAJBgNVBAYTAlJVMTMwMQYDVQQIDCo2NiDQodCy0LXRgNC00LvQvtCy0YHQutCw0Y8g0L7QsdC70LDRgdGC0YwxITAfBgNVBAcMGNCV0LrQsNGC0LXRgNC40L3QsdGD0YDQszFEMEIGA1UECQw70YPQu9C40YbQsCDQndCw0YDQvtC00L3QvtC5INCy0L7Qu9C4LCDRgdGC0YDQvtC10L3QuNC1IDE50JAxMDAuBgNVBAsMJ9Cj0LTQvtGB0YLQvtCy0LXRgNGP0Y7RidC40Lkg0YbQtdC90YLRgDEpMCcGA1UECgwg0JDQniAi0J_QpCAi0KHQmtCRINCa0L7QvdGC0YPRgCIxKTAnBgNVBAMMINCQ0J4gItCf0KQgItCh0JrQkSDQmtC-0L3RgtGD0YAiMGYwHwYIKoUDBwEBAQEwEwYHKoUDAgIjAQYIKoUDBwEBAgIDQwAEQOZuawyTwpSv9K_folowuvKk3pt-sreD6cbYCJx8JrXHzFg879oC9FBZ_1XGYLt1T_ScPYHdO0-_ngXKiC_QpLGjggRGMIIEQjALBgNVHQ8EBAMCAYYwHQYDVR0OBBYEFM-bXH4Np-2K0ytIc0ovtNuZXnFiMBIGA1UdEwEB_wQIMAYBAf8CAQAwJQYDVR0gBB4wHDAIBgYqhQNkcQEwCAYGKoUDZHECMAYGBFUdIAAwVAYFKoUDZG8ESwxJItCa0YDQuNC_0YLQvtCf0YDQviBDU1AiICjQstC10YDRgdC40Y8gNC4wKSAo0LjRgdC_0L7Qu9C90LXQvdC40LUgMi1CYXNlKTAUBgkrBgEEAYI3FAIEBwwFU3ViQ0EwEgYJKwYBBAGCNxUBBAUCAwQABDCCAX0GA1UdIwSCAXQwggFwgBTJE1ixTKdiOn7SPzym5xR8nXCjhqGCAUOkggE_MIIBOzEhMB8GCSqGSIb3DQEJARYSZGl0QGRpZ2l0YWwuZ292LnJ1MQswCQYDVQQGEwJSVTEYMBYGA1UECAwPNzcg0JzQvtGB0LrQstCwMRkwFwYDVQQHDBDQsy4g0JzQvtGB0LrQstCwMVMwUQYDVQQJDErQn9GA0LXRgdC90LXQvdGB0LrQsNGPINC90LDQsdC10YDQtdC20L3QsNGPLCDQtNC-0LwgMTAsINGB0YLRgNC-0LXQvdC40LUgMjEmMCQGA1UECgwd0JzQuNC90YbQuNGE0YDRiyDQoNC-0YHRgdC40LgxGDAWBgUqhQNkARINMTA0NzcwMjAyNjcwMTEVMBMGBSqFA2QEEgo3NzEwNDc0Mzc1MSYwJAYDVQQDDB3QnNC40L3RhtC40YTRgNGLINCg0L7RgdGB0LjQuIIRAJUfo0d8YQQ6rfqFhieCNEIwgY8GA1UdHwSBhzCBhDAqoCigJoYkaHR0cDovL3JlZXN0ci1wa2kucnUvY2RwL2d1YzIwMjIuY3JsMCqgKKAmhiRodHRwOi8vY29tcGFueS5ydC5ydS9jZHAvZ3VjMjAyMi5jcmwwKqAooCaGJGh0dHA6Ly9yb3N0ZWxlY29tLnJ1L2NkcC9ndWMyMDIyLmNybDBABggrBgEFBQcBAQQ0MDIwMAYIKwYBBQUHMAKGJGh0dHA6Ly9yZWVzdHItcGtpLnJ1L2NkcC9ndWMyMDIyLmNydDCB9QYFKoUDZHAEgeswgegMNNCf0JDQmtCcIMKr0JrRgNC40L_RgtC-0J_RgNC-IEhTTcK7INCy0LXRgNGB0LjQuCAyLjAMQ9Cf0JDQmiDCq9CT0L7Qu9C-0LLQvdC-0Lkg0YPQtNC-0YHRgtC-0LLQtdGA0Y_RjtGJ0LjQuSDRhtC10L3RgtGAwrsMNdCX0LDQutC70Y7Rh9C10L3QuNC1IOKEliAxNDkvMy8yLzIvMjMg0L7RgiAwMi4wMy4yMDE4DDTQl9Cw0LrQu9GO0YfQtdC90LjQtSDihJYgMTQ5LzcvNi00NDkg0L7RgiAzMC4xMi4yMDIxMAwGBSqFA2RyBAMCAQEwCgYIKoUDBwEBAwIDQQDEcACCKusujAkQVeK3cBbZHRjJFNdDg67LC-rL4QqNzsIFQrnumuxy0iA8jpQkz3GHQP67IzBhiCHed4_qwJHdMIIJ1TCCCYKgAwIBAgIRBGo5bgCOr2KMSXgFIdj2LWwwCgYIKoUDBwEBAwIwggGEMRUwEwYFKoUDZAQSCjY2NjMwMDMxMjcxHjAcBgkqhkiG9w0BCQEWD2NhQHNrYmtvbnR1ci5ydTEYMBYGBSqFA2QBEg0xMDI2NjA1NjA2NjIwMQswCQYDVQQGEwJSVTEzMDEGA1UECAwqNjYg0KHQstC10YDQtNC70L7QstGB0LrQsNGPINC-0LHQu9Cw0YHRgtGMMSEwHwYDVQQHDBjQldC60LDRgtC10YDQuNC90LHRg9GA0LMxRDBCBgNVBAkMO9GD0LvQuNGG0LAg0J3QsNGA0L7QtNC90L7QuSDQstC-0LvQuCwg0YHRgtGA0L7QtdC90LjQtSAxOdCQMTAwLgYDVQQLDCfQo9C00L7RgdGC0L7QstC10YDRj9GO0YnQuNC5INGG0LXQvdGC0YAxKTAnBgNVBAoMINCQ0J4gItCf0KQgItCh0JrQkSDQmtC-0L3RgtGD0YAiMSkwJwYDVQQDDCDQkNCeICLQn9CkICLQodCa0JEg0JrQvtC90YLRg9GAIjAeFw0yMzAxMTgwNjM2MTlaFw0yNDAxMTgwNjMzNDNaMIIBrzEVMBMGBSqFA2QEEgo3NzA1NDI0NTA5MSgwJgYJKoZIhvcNAQkBFhltZWdvcm92QHZvc3Rvay1lbGVjdHJhLnJ1MRowGAYIKoUDA4EDAQESDDQ1MDExOTE4NDA3NjEWMBQGBSqFA2QDEgsxMjA3MDkyNzIyNDEYMBYGBSqFA2QBEg0xMDM3NzM5MTIzNjk2MSgwJgYDVQQMDB_QvdCw0YfQsNC70YzQvdC40Log0L7RgtC00LXQu9CwMSIwIAYDVQQKDBnQkNCeICLQrdCaICLQktCe0KHQotCe0JoiMSkwJwYDVQQJDCDQo9CbINCR0KPQoNCU0JXQndCa0J4sINCU0J7QnCAyMjEVMBMGA1UEBwwM0JzQvtGB0LrQstCwMRwwGgYDVQQIDBM3NyDQsy4g0JzQvtGB0LrQstCwMQswCQYDVQQGEwJSVTEoMCYGA1UEKgwf0JzQsNC60YHQuNC8INCR0L7RgNC40YHQvtCy0LjRhzEVMBMGA1UEBAwM0JXQs9C-0YDQvtCyMSIwIAYDVQQDDBnQkNCeICLQrdCaICLQktCe0KHQotCe0JoiMGYwHwYIKoUDBwEBAQEwEwYHKoUDAgIkAAYIKoUDBwEBAgIDQwAEQLtTuQ5yNBAo2lMpu4e0d66x9zJxhRKSfTk-wlWJ7UClfT53SxaFi_lCWJcLXQQcG_IyduEffzkB0UbQ2NDS8xijggWXMIIFkzAMBgUqhQNkcgQDAgEBMA4GA1UdDwEB_wQEAwIE8DAkBgNVHREEHTAbgRltZWdvcm92QHZvc3Rvay1lbGVjdHJhLnJ1MBMGA1UdIAQMMAowCAYGKoUDZHEBMDkGA1UdJQQyMDAGCCsGAQUFBwMCBgcqhQMCAiIGBggrBgEFBQcDBAYIKoUDAwUKAgwGByqFAwMHCAEwgdkGCCsGAQUFBwEBBIHMMIHJMDgGCCsGAQUFBzABhixodHRwOi8vcGtpLnNrYmtvbnR1ci5ydS9vY3NwY2FxMjAxMi9vY3NwLnNyZjBFBggrBgEFBQcwAoY5aHR0cDovL2NkcC5za2Jrb250dXIucnUvY2VydGlmaWNhdGVzL3NrYmtvbnR1ci1xLTIwMjIuY3J0MEYGCCsGAQUFBzAChjpodHRwOi8vY2RwMi5za2Jrb250dXIucnUvY2VydGlmaWNhdGVzL3NrYmtvbnR1ci1xLTIwMjIuY3J0MCsGA1UdEAQkMCKADzIwMjMwMTE4MDYzNjE5WoEPMjAyNDAxMTgwNjMzNDNaMIIBMwYFKoUDZHAEggEoMIIBJAwrItCa0YDQuNC_0YLQvtCf0YDQviBDU1AiICjQstC10YDRgdC40Y8gNC4wKQxTItCj0LTQvtGB0YLQvtCy0LXRgNGP0Y7RidC40Lkg0YbQtdC90YLRgCAi0JrRgNC40L_RgtC-0J_RgNC-INCj0KYiINCy0LXRgNGB0LjQuCAyLjAMT9Ch0LXRgNGC0LjRhNC40LrQsNGCINGB0L7QvtGC0LLQtdGC0YHRgtCy0LjRjyDihJYg0KHQpC8xMjQtMzk3MSDQvtGCIDE1LjAxLjIwMjEMT9Ch0LXRgNGC0LjRhNC40LrQsNGCINGB0L7QvtGC0LLQtdGC0YHRgtCy0LjRjyDihJYg0KHQpC8xMjgtNDI3MCDQvtGCIDEzLjA3LjIwMjIwIwYFKoUDZG8EGgwYItCa0YDQuNC_0YLQvtCf0YDQviBDU1AiMHoGA1UdHwRzMHEwNqA0oDKGMGh0dHA6Ly9jZHAuc2tia29udHVyLnJ1L2NkcC9za2Jrb250dXItcS0yMDIyLmNybDA3oDWgM4YxaHR0cDovL2NkcDIuc2tia29udHVyLnJ1L2NkcC9za2Jrb250dXItcS0yMDIyLmNybDCBggYHKoUDAgIxAgR3MHUwZRZAaHR0cHM6Ly9jYS5rb250dXIucnUvYWJvdXQvZG9jdW1lbnRzL2NyeXB0b3Byby1saWNlbnNlLXF1YWxpZmllZAwd0KHQmtCRINCa0L7QvdGC0YPRgCDQuCDQlNCX0J4DAgXgBAzljwsRoaSA_xG9eQ4wggF2BgNVHSMEggFtMIIBaYAUz5tcfg2n7YrTK0hzSi-025lecWKhggFDpIIBPzCCATsxITAfBgkqhkiG9w0BCQEWEmRpdEBkaWdpdGFsLmdvdi5ydTELMAkGA1UEBhMCUlUxGDAWBgNVBAgMDzc3INCc0L7RgdC60LLQsDEZMBcGA1UEBwwQ0LMuINCc0L7RgdC60LLQsDFTMFEGA1UECQxK0J_RgNC10YHQvdC10L3RgdC60LDRjyDQvdCw0LHQtdGA0LXQttC90LDRjywg0LTQvtC8IDEwLCDRgdGC0YDQvtC10L3QuNC1IDIxJjAkBgNVBAoMHdCc0LjQvdGG0LjRhNGA0Ysg0KDQvtGB0YHQuNC4MRgwFgYFKoUDZAESDTEwNDc3MDIwMjY3MDExFTATBgUqhQNkBBIKNzcxMDQ3NDM3NTEmMCQGA1UEAwwd0JzQuNC90YbQuNGE0YDRiyDQoNC-0YHRgdC40LiCCjRlJ8MAAAAABtMwHQYDVR0OBBYEFD5tGfzyaVrtBU8M4LBFz39MEPJnMAoGCCqFAwcBAQMCA0EAfONOwnVlUmNyzXR3eB5gG4_TLO4asFALAc5c-xOd-c8FtVNyT8wGBVW-lHLYJffTEE-81eysZyRYZenhPC2axjGCAgAwggH8AgEBMIIBmzCCAYQxFTATBgUqhQNkBBIKNjY2MzAwMzEyNzEeMBwGCSqGSIb3DQEJARYPY2FAc2tia29udHVyLnJ1MRgwFgYFKoUDZAESDTEwMjY2MDU2MDY2MjAxCzAJBgNVBAYTAlJVMTMwMQYDVQQIDCo2NiDQodCy0LXRgNC00LvQvtCy0YHQutCw0Y8g0L7QsdC70LDRgdGC0YwxITAfBgNVBAcMGNCV0LrQsNGC0LXRgNC40L3QsdGD0YDQszFEMEIGA1UECQw70YPQu9C40YbQsCDQndCw0YDQvtC00L3QvtC5INCy0L7Qu9C4LCDRgdGC0YDQvtC10L3QuNC1IDE50JAxMDAuBgNVBAsMJ9Cj0LTQvtGB0YLQvtCy0LXRgNGP0Y7RidC40Lkg0YbQtdC90YLRgDEpMCcGA1UECgwg0JDQniAi0J_QpCAi0KHQmtCRINCa0L7QvdGC0YPRgCIxKTAnBgNVBAMMINCQ0J4gItCf0KQgItCh0JrQkSDQmtC-0L3RgtGD0YAiAhEEajluAI6vYoxJeAUh2PYtbDAKBggqhQMHAQECAjAKBggqhQMHAQEBAQRAgwew7-wPvAGifi0JmmwCFqbfdnVy2B3vhr9qeWHKlDq5hTNrpxy3RupT_NGdXpKAAc7DWgB8FPhcwB-UQ5tdpA

Весь код, кроме инициализации LibCore.Initializer.Initialize(); идентичный, однако на .net 6 signedCms.Encode() возвращает массив из 5155 байт, а на .net 4.7.2 из 5770 байт. Сертификат используется один и тот же, подписывается тот же uuid.

**Comment by Fasjeit** [comment]
Подписал файл через CryptoPro.Net и через LibCore. Разница в размерах действительно есть.
Судя по всему 4.6+ добавляет атрибуты по умолчанию, в то время как в core их нет. На 3.1+ аналогичное поведение.

Возможно дело как раз в отсутствии атрибутов (см `[0]` ниже).

![изображение](https://user-images.githubusercontent.com/15075638/217506791-7a34570b-eb5a-4825-9c33-1808f0276eab.png)

Атрибуты кроме `signingCertificateV2` можно выставить так
```csharp
cmsSigner.SignedAttributes.Add(new Pkcs9SigningTime(DateTime.Now));
```

Как выставить в коде `signingCertificateV2` (если и он действительно нужен) - хороший вопрос.
Структура объявлена тут - [SigningCertificateV2Asn](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Asn1/SigningCertificateV2Asn.xml.cs), но используется только на декодирование (тут [TimestampTokenTests](https://github.com/dotnet/runtime/blob/c80a49d151b5e642be419067adf401a365b624b7/src/libraries/System.Security.Cryptography.Pkcs/tests/Rfc3161/TimestampTokenTests.cs))

Генерацию структуры ms делать не хотят - https://github.com/dotnet/runtime/issues/27351#issuecomment-420340015
Возможно придётся собирать её руками.

Попробуйте выставит атрибуты, кроме `SigningCertificateV2Asn`, может заработает и без него.

**Comment by Fasjeit** [comment]
Есть предположение, что в core Cms собирается руками, в то время как в Net Framework использовались вызовы pkcs, которые сами проставляли атрибуты.
https://cpdn.cryptopro.ru/content/csp40/html/cadesattrs.html

**Comment by SergeyKobyakov** [comment]
Это помогло;
```sharp
cmsSigner.SignedAttributes.Add(new Pkcs9SigningTime(DateTime.Now));
```
Спасибо вам огромное!!

**Comment by Fasjeit** [comment]
Раз прикладная задача решена - закрываю. 

Если кому то понадобится `signingCertificateV2` - будем решать отдельно, возможно сборкой через AsnWriter.
