### ISSUE TITLE
Запрашивает пароль для контейнера

### ISSUE THREAD

**Issue by Jenevra** [CryptoPro/libcore#54]
Добрый день.

При чтении сертификата сталкиваемся с тем, что требуется ввести пароль для контейнера:
```C#
var certificate = new CpX509Certificate2("/.../34112001.pfx");
```

![image](https://github.com/CryptoPro/libcore/assets/13356696/9c52a51f-62fe-458c-ab4d-dc18380e735d)

Скажите, пожалуйста, как можно от этого избавиться? Приложение планируется запускать в кубернетесе в контейнере, там не будет такой возможности как вводить пароль и подтверждать это действие.

**Comment by Fasjeit** [comment]
Добрый день.

Программно пин-код на контейнер ключа можно указать используя метод `SetContainerPassword(...)` для объектов типа `Gost_xxx_CryptoServiceProvider`. Вызывать этот метод нужно **до** первого обращения к ключу.

Т.е. последовательность действий такая.

   * Получаем объект криптопровайдера для закрытого ключа.
   * Вызываем метод SetContainerPassword, передавая ему корректный пин для контейнера ключа.
   * Используем объект криптопровайдера для осуществления криптографических операций.

Проверка корректности переданного пин-кода будет производиться только в момент обращения к ключу (т.е. на шаге 3.).

**Comment by Fasjeit** [comment]
Хм. Окошко, которое отображается у вас запрашивает пин на новый контейнер (который вы только что создали открыв pfx без флага `EphemeralKeySet` (новая версия), `CspNoPersistKeySet` (старая версия)). При таком окрытии pfx происходит создание ключевого контейнера с закртым ключом сертификата, которое и кидает ваше окошко.

**Comment by Fasjeit** [comment]
Альтернативный путь - установка сертификата в хранилище при создании контейнера.
Подробнее можно посмотреть тут - https://github.com/CryptoPro/libcore/issues/21#issuecomment-1552693076

**Comment by Jenevra** [comment]
Помогло чтение сертификата вот так:
```C#
var certificate = new CpX509Certificate2("/.../34112001.pfx", "", X509KeyStorageFlags.EphemeralKeySet);
```

**Comment by Jenevra** [comment]
Спасибор за помощь!
