### ISSUE TITLE
Работа с сертификатом на флешке

### ISSUE THREAD

**Issue by Jenevra** [CryptoPro/libcore#55]
Добрый день.

Не могли бы вы подсказать, как работать с библиотекой libcore и сертификатом, который находится на токене (флешке).
Понимаю, как загружать сертификат, когда у нас есть pfx файл, например, но из примеров в документации, которые есть на сайте, не совсем понятно как можно загружать сертификат с токена (флешки)  в коде.

**Comment by Fasjeit** [comment]
Добрый день. Необходимо установить сертификат в хранилище с привязкой к контейнеру закрытого ключа (который останется на токене) Далее просто работаете как с обычным сертификатом в хранилище.

**Comment by Fasjeit** [comment]
Альтернативно можно попробовать напрямую обращаться к контейнеру ключа при вставленном токене.
Для работы с контейнерами ключа необходимо создать объект криптопровайдера `Gost_xxx`, передав имя контейнера в `CpCspParameters` (новая версия) /`CspParameters` (старая версия).

**Comment by Jenevra** [comment]
Хорошо, спасибо большое, будем пробовать.
