### ISSUE TITLE
libcore + JWT

### ISSUE THREAD

**Issue by Jenevra** [CryptoPro/libcore#60]
Добрый день.

А есть ли в libcore поддержка JWT?
Необходимо получить JWT токен с помощью ГОСТ сертификата.

**Comment by yodasad** [comment]
Добрый день!

Отдельных объектов для работы с JWT нет.

В основном в JWT используется т.н. необработанная подпись (RAW), которую можно создать, например, с помощью класса `Gost3410_2012_256CryptographicServiceProvider`.

По форматам заголовков (идентификаторы алгоритмов, алгоритмы подписи и т.д.) ориентируйтесь на требования системы, в который токены будут использоваться, например, за основу можно взять формат JWT от ЕСИА.
Пример проверки токена можно посмотреть в [запросе](https://github.com/CryptoPro/libcore/issues/45), создание симметрично.

**Comment by Jenevra** [comment]
Поняла, спасибо большое за ответ
