### ISSUE TITLE
Не устанавливается не извлекатся ключ на симметричном алгоритме шифрования

### ISSUE THREAD

**Issue by sentaniel** [CryptoPro/libcore#61]
using var gost = new Gost28147CryptoServiceProvider();
        using var keyGen = new GostRngCryptoServiceProvider();
        var key = new byte[32];
        keyGen.GetBytes(key);
        gost.Key = key;
пытаюсь установить ключ чтобы его в дальнейшем использовать для расшифровки публичного ключа сертификата. При записи и чтении свойства gost.Key возвращает всегда null

**Comment by Fasjeit** [comment]
Добрый день.

Для секретных ключей в настоящий момент запрещён экспорт и импорт ключей в "сыром" виде. Для долгосрочного хранения симметричных ключей часто используют их экспорт на долговременном асимметричном ключе. Подробнее можно посмотреть в [документации](https://dss.cryptopro.ru/libcore/docs/04-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B/04-06-%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B2%D0%BE%D0%B9-%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D1%80%D1%82.html).

Дабы избежать [проблемы XY](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0_XY) попрошу более подробно описать задачу, которую вы пытаетесь решить, ибо необходимость шифровать открытый ключ сертификата на долговременном симметричном ключе, который вы хотите экспортировать в сыром виде кажется весьма нестандартной.

**Comment by sentaniel** [comment]
Добрый день, задача следующая.

**Comment by sentaniel** [comment]
Добрый день, задача следующая.

**Comment by sentaniel** [comment]
Добрый день.
Задача следующая.
Реализовать метод симметричным алгоритмом шифрующий публичный ключ сертификата. Который возвращает следующую модель
/// <summary>
/// Параметры для SymmetricAlgorithm
/// </summary>
public class SymmetricAlgorithmParams
{
    /// <summary>
    /// Ключ
    /// </summary>
    public string Key{ get; set; }
    /// <summary>
    /// данные о диверсификации ключа
    /// </summary>
    public string DiversData{ get; set; }
    /// <summary>
    /// вектор инициализации
    /// </summary>
    public string Iv{ get; set; }
}

соответсвенно с помощью этих данных в дальнешем необходимо уметь шифровать и расшифровывать какие-то данные
    
	Task<byte[]> EncryptSymmetric(byte[] content, SymmetricAlgorithmParams algorithmParams);
	Task<byte[]> DecryptSymmetric(byte[] content, SymmetricAlgorithmParams algorithmParams);

**Comment by Fasjeit** [comment]
Зачем изначально шифровать открытый ключ сертификата на симметричном ключе?

**Comment by Fasjeit** [comment]
Симметричные ключи можно экспортировать только на асимметричном ключе, или другом симметричном ключе. 
Примеры есть по ссылки в доке выше.

т.е.
 - генерируете симметричный ключ (создаёте объект Gost28147CryptoServiceProvider) или импортируете на долговременном асимметричном ключе
 - используете ключ для шифрования\расшифровывания
 - экспортируете ключ для долговременного хранения на долговременном асимметричном ключе (в случае надобности)

**Comment by Fasjeit** [comment]
Альтернативно можно посмотреть в сторону PrfGostXXXX, в котором можно указать сырой ключ для prf и получить симметричный ключ через метод DeriveKey.

Подробнее об алгоритме выработки и параметрах см [Р 50.1.113-2016](https://tc26.ru/standard/rs/%D0%A0%2050.1.113-2016.pdf)

**Comment by sentaniel** [comment]
А подскажите в какой версии библиотеки можно PrfGost3411_2012_256 найти? В релизной последней версии LibCore.Windows 2024.1.10.1 не нашел такого класса.

**Comment by Fasjeit** [comment]
См последний пре-релиз.
https://github.com/CryptoPro/libcore/releases/tag/v2024.4.17

**Comment by sentaniel** [comment]
Спасибо, еще один вопрос для Gost3410_2012_256CryptoServiceProvider вижу убрали метод Encrypt который ранее был не реализованным. Есть где-то пример как можно зашифровать на основе публичного ключа сертификата этим алгоритмом?

**Comment by Fasjeit** [comment]
Асимметрично зашифровать в сторону открытого ключа можно только другой ключ.

Если вам необходимо зашифровать данные в сторону открытого ключа, то вам нужно
- создать сессионный симметричный ключ
- зашифровать данные на симметричном ключе
- зашифровать симметричный ключ в сторону открытого ключа

Примеры можно посмотреть в [документации](https://dss.cryptopro.ru/libcore/docs/04-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B/04-06-%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B2%D0%BE%D0%B9-%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D1%80%D1%82.html#asymmetric-keyexchange-key-encryption) и в [старый тестах](https://github.com/CryptoPro/corefx/blob/e6e012d7e377fc5e1cf4d9d5872c117714e9bd63/src/System.Security.Cryptography.Csp/tests/GostKeyExchangeTests.cs#L184)

Альтернативно можно воспользоваться [CMS](https://dss.cryptopro.ru/libcore/docs/04-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B/04-09-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-enveloped-cms.html) или [XML](https://github.com/CryptoPro/corefx/blob/master/src/System.Security.Cryptography.Xml/tests/GostEncryptedXmlTest.cs) шифрованием.

**Comment by sentaniel** [comment]
Я видел эти примеры и именно так и реализовал. Но возникает проблема, что в плагине и в коде серверном на Php (который собственно пытаемся переписать на .Net) с использование библиотеки CryptoPro  используется еще дополнительно по мимо сессионого ключа и вектора DiversData. Нашли ссылку на форум 4х летней давности https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=18740 с аналогичным вопросом для старой версии библиотеки Sharpei. И в ответе там сказано что надо использовать Crypto-Pro CAdES 1.0 Type Library

**Comment by Fasjeit** [comment]
Если нужна совместимость с cades то пока единственный вариант использовать p/invoke + cades. В libcore не реализована диверсификация, используемая в cades и работа с блобами типа PUBLICKEYBLOBEX.

Если задача сделать что то похожее то можно использовать PRF + KeyExchange, как было указано выше.
