### ISSUE TITLE
и снова "SignatureDescription could not be created for the signature algorithm supplied" при подписи

### ISSUE THREAD

**Issue by Lord207** [CryptoPro/libcore#64]
День добрый, в _https://github.com/CryptoPro/libcore/issues/51_ это уже было, но вопрос актуален.

пример Ваш же из #51, на **signedXml.ComputeSignature()** получаю указанную ошибку.
ОС Windows 10 Pro (10.0.19045 Н/Д построение 19045)
**Core 6, 8** не важно. 
CryptoPro CSP **5.0.13000** КС1
LibCore пробовал **2024.2.29, 2024.4.17**
Сертификат:
![image](https://github.com/CryptoPro/libcore/assets/26308710/23efb339-3848-41d1-b7c1-82f44a272aa0)

в консоли вижу такое:
![image](https://github.com/CryptoPro/libcore/assets/26308710/4cc69451-8d6e-4e79-92a7-906752fc298e)
и чтото мне тут про манифест и файлнотфоунд не нравится

проект целиком в архиве:
[AstraCertificate.zip](https://github.com/user-attachments/files/15789405/AstraCertificate.zip)

**Comment by Fasjeit** [comment]
Добрый день.

Спасибо за проект, удалось воспроизвести. В проекте не хватает зависимости от `System.Security.Xml`, добавить его можно так:

```csproj
<PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.0" />
```

После этого должно заработать. С версией `8.0.1` (текущая на данный момент) тоже должно отрабатывать.

Пакеты `xml` и `pkcs` в текущих версиях требуют указания "родных" пакетов от ms (они используют часть родных методов + затягивают ресурсы для текстовок ошибок). В доке данный момент не указан, проглядели. Поправим к сл. релизу и/или посмотрим, не сломаем ли что то, если укажем явные зависимости в пакетах.

**Comment by Lord207** [comment]
Подтверждаю, с указанием этого пакета взлетело, спасибо!
осталось на Астре проверить, но думаю там то же самое д.б.

**Comment by Fasjeit** [comment]
Отлично, тогда закрываю. Если будут какие то проблемы - можно переоткрыть. 

В сл релизе (надеюсь на сл. неделе) будет исправлено.

**Comment by kovalusion** [comment]
Приветствую. 
Дополню. Бился над той же ошибкой, пока не полез в менеджер пакетов проверить зависимости. В CryptoPro.Security.Cryptography.Pkcs обнаружилась зависимость от System.Security.Cryptography.Pkcs

<img width="426" height="451" alt="Image" src="https://github.com/user-attachments/assets/0669e903-e7c3-422c-96ae-e9771ce75cd6" />

После явного добавления соответствующего пакета все разрешилось. Итоговый набор пакетов для примера из документации  на скрине:

<img width="312" height="169" alt="Image" src="https://github.com/user-attachments/assets/0a36fc35-acc1-43f0-9bc3-a9f35369bbb9" />

Уже после поста наткнулся на открытый issue [#79 Неверные зависимости](https://github.com/CryptoPro/libcore/issues/79) Похоже что связано, ну да пусть будет)
