### ISSUE TITLE
store.Certificates.Find не находит сертификат открытого ключа. Linux

### ISSUE THREAD

**Issue by LebedevaNA** [CryptoPro/libcore#66]
Добрый день.
Вот так пытаюсь извлечь сертификат:
```
CpX509Certificate2 GetEsiaSignerCert()
{
var store = new CpX509Store(StoreName.Root, StoreLocation.CurrentUser);
store.Open(OpenFlags.OpenExistingOnly | OpenFlags.ReadOnly);
var certificates = store.Certificates.Find(X509FindType.FindBySerialNumber, _esiaOptions.EsiaCertSerialNumber, false); //<<---пусто

var certificate = certificates[0];

return certificate;
}
```
store.Certificates.Find возвращает пустую коллекцию. 
сертификат установлен вот так: 
RUN /opt/cprocsp/bin/amd64/certmgr -inst -cert -file TESIA_GOST_2012_new.cer -store uRoot | echo 'o'

все развернуто в докер контейнере на debian 11. При этом из под windows все работает как надо. 

библиотеки в приложении:
```
<PackageReference Include="CryptoPro.Net.Security" Version="2024.6.18"/>
<PackageReference Include="CryptoPro.Security.Cryptography" Version="2024.6.18"/>
<PackageReference Include="CryptoPro.Security.Cryptography.Pkcs" Version="2024.6.18"/>
<PackageReference Include="CryptoPro.Security.Cryptography.Xml" Version="2024.6.18"/>
```
само приложение на .net 6
версия csp v5.0.10013 KC1 Release Ver:5.0.13000

**Comment by Fasjeit** [comment]
Добрый день.

Первым делом стоит обновить csp до актуальной версии (5.0.13000), как указано в документации.

Для сертификата из вложения текущего сообщения удалось получить его следующим образом:
```csharp
// 0x02490ADB005CB1DC9B4C7B9FCDD7A58D32
using (var store = new CpX509Store(StoreName.Root, StoreLocation.CurrentUser))
{
    store.Open(OpenFlags.ReadOnly);
    var serial = "02490adb005cb1dc9b4c7b9fcdd7a58d32";
    var found = store.Certificates.Find(X509FindType.FindBySerialNumber, serial, false);
    var foundCert = found[0];
}
```
Убедитесь, что вы установили сертификат используя команду `/opt/cprocsp/bin/amd64/certmgr -list` и что передаёте корректное значение серийного номера.

Если ошибка сохраняется - подготовьте небольшой тестовый проект (csproj + исходники + сертификат) на котором воспроизводите ошибку.

[TESIA GOST 2012 new.zip](https://github.com/user-attachments/files/15914364/TESIA.GOST.2012.new.zip)
