### ISSUE TITLE
CheckSignature всегда возвращает false

### ISSUE THREAD

**Issue by SwimUp** [CryptoPro/libcore#68]
Добрый день. Пытаюсь подписать XML и проверить её подпись по документации https://dss.cryptopro.ru/libcore/docs/04-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B/04-03-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-xml-%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D0%B8.html

Проблема в том, что подписанная хмл не проходит проверку, CheckSignature всегда возвращает false, при этом на сайте https://saas.cryptopro.ru/verifycpca/#/signature подпись проверку проходит.

Спека:
.NET 8.0
LibCore 27.06.2024
Windows 10
CryptoPro CSP 4.0 

На вход подаю XML
```xml
<?xml version="1.0" encoding="utf-8"?>
<CoordinateTaskMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<CoordinateTaskDataMessage>
		<Task>
			<MessageId>c9d37a8b-04ae-41f3-b371-8637c3b85f84</MessageId>
		</Task>
	</CoordinateTaskDataMessage>
</CoordinateTaskMessage>
```

Затем, читаю + подписываю
```csharp
using (var store = new CpX509Store(StoreName.My, StoreLocation.CurrentUser))
{
    store.Open(OpenFlags.ReadOnly);
    var storeCerts = store.Certificates;

    var CpCertificate = store.Certificates.Find(X509FindType.FindByThumbprint, "<мой серт>", true)[0];

    XmlDocument xmlDocument = new XmlDocument();
    xmlDocument.Load("out.xml");

    var sig = SignXmlFile(xmlDocument, CpCertificate.GetGost3410_2012_256PrivateKey(), CpCertificate);

    File.WriteAllText("out-signed-text.xml", sig.OuterXml, Encoding.UTF8);

    var cc = ValidateXmlFIle(sig);
}
```

Методы подписания и проверки просто копипаста с доков.

Проверял способ подписания и проверки на .net framework 4.7.2, непосредственно с либами криптопро - там подпись проверку проходит.

**Comment by SwimUp** [comment]
Обновление до 5 версии помогло, метод стал отдавать true. Есть идеи, почему на framework-е CheckSignature true отдает и на 4 версии?

**Comment by Fasjeit** [comment]
Для корректной работы Libcore требуется последняя актуальная версия csp 5.0, как указанно [в документации](https://dss.cryptopro.ru/libcore/docs/02-%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B/02-00-%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B.html#%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%BF%D1%80%D0%BE-csp).

В более старых версиях csp может отсутствовать требуемая функциональность необходима для корректной работы, так как код работы с сертификатами и XML Был полностью переписан, по сравнению с версией КриптоПро.Net для .net Framework.
