### ISSUE TITLE
NotSupprotedException

### ISSUE THREAD

**Issue by ParadiseFallen** [CryptoPro/libcore#8]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/50731756/219364771-31371af7-af38-42d9-96d5-940d8e131650.png">
Win11
Код из примера

**Comment by ParadiseFallen** [comment]
<img width="272" alt="image" src="https://user-images.githubusercontent.com/50731756/219370419-e801313a-eace-48f3-824d-002d4b0d0e66.png">
Проект стоит на net6

**Comment by Fasjeit** [comment]
Судя по путям - ОС Windows, необходимо использовать обычный `X509Store`, как указанно в [Readme](https://github.com/CryptoPro/libcore#-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-%D1%81%D0%B5%D1%80%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%B0-%D0%B8%D0%B7-%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0).

```csharp
// windows, using X509Store
using (var store = new X509Store(StoreName.My, StoreLocation.CurrentUser))
{
    store.Open(OpenFlags.ReadOnly);
    var cert = store.Certificates.Find(X509FindType.FindBySubjectName, "G2012256", false)[0];
}
```
